# -*- coding: utf-8 -*-

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from .user_action_reference import UserActionReference
from .io import (
    GcsSource,
    GcsDestination,
    BigQuerySource,
    BigQueryDestination,
    ContainerRegistryDestination,
)
from .env_var import EnvVar
from .machine_resources import (
    MachineSpec,
    DedicatedResources,
    AutomaticResources,
    BatchDedicatedResources,
    ResourcesConsumed,
)
from .custom_job import (
    CustomJob,
    CustomJobSpec,
    WorkerPoolSpec,
    ContainerSpec,
    PythonPackageSpec,
    Scheduling,
)
from .study import (
    Trial,
    StudySpec,
    Measurement,
)
from .hyperparameter_tuning_job import HyperparameterTuningJob
from .manual_batch_tuning_parameters import ManualBatchTuningParameters
from .dataset import (
    Dataset,
    ImportDataConfig,
    ExportDataConfig,
)
from .deployed_model_ref import DeployedModelRef
from .explanation_metadata import ExplanationMetadata
from .explanation import (
    Explanation,
    ModelExplanation,
    Attribution,
    ExplanationSpec,
    ExplanationParameters,
    SampledShapleyAttribution,
)
from .model import (
    Model,
    PredictSchemata,
    ModelContainerSpec,
    Port,
)
from .training_pipeline import (
    TrainingPipeline,
    InputDataConfig,
    FractionSplit,
    FilterSplit,
    PredefinedSplit,
    TimestampSplit,
)
from .pipeline_service import (
    CreateTrainingPipelineRequest,
    GetTrainingPipelineRequest,
    ListTrainingPipelinesRequest,
    ListTrainingPipelinesResponse,
    DeleteTrainingPipelineRequest,
    CancelTrainingPipelineRequest,
)
from .operation import (
    GenericOperationMetadata,
    DeleteOperationMetadata,
)
from .specialist_pool import SpecialistPool
from .specialist_pool_service import (
    CreateSpecialistPoolRequest,
    CreateSpecialistPoolOperationMetadata,
    GetSpecialistPoolRequest,
    ListSpecialistPoolsRequest,
    ListSpecialistPoolsResponse,
    DeleteSpecialistPoolRequest,
    UpdateSpecialistPoolRequest,
    UpdateSpecialistPoolOperationMetadata,
)
from .endpoint import (
    Endpoint,
    DeployedModel,
)
from .data_item import DataItem
from .annotation import Annotation
from .annotation_spec import AnnotationSpec
from .dataset_service import (
    CreateDatasetRequest,
    CreateDatasetOperationMetadata,
    GetDatasetRequest,
    UpdateDatasetRequest,
    ListDatasetsRequest,
    ListDatasetsResponse,
    DeleteDatasetRequest,
    ImportDataRequest,
    ImportDataResponse,
    ImportDataOperationMetadata,
    ExportDataRequest,
    ExportDataResponse,
    ExportDataOperationMetadata,
    ListDataItemsRequest,
    ListDataItemsResponse,
    GetAnnotationSpecRequest,
    ListAnnotationsRequest,
    ListAnnotationsResponse,
)
from .endpoint_service import (
    CreateEndpointRequest,
    CreateEndpointOperationMetadata,
    GetEndpointRequest,
    ListEndpointsRequest,
    ListEndpointsResponse,
    UpdateEndpointRequest,
    DeleteEndpointRequest,
    DeployModelRequest,
    DeployModelResponse,
    DeployModelOperationMetadata,
    UndeployModelRequest,
    UndeployModelResponse,
    UndeployModelOperationMetadata,
)
from .model_evaluation import ModelEvaluation
from .completion_stats import CompletionStats
from .batch_prediction_job import BatchPredictionJob
from .model_evaluation_slice import ModelEvaluationSlice
from .model_service import (
    UploadModelRequest,
    UploadModelOperationMetadata,
    UploadModelResponse,
    GetModelRequest,
    ListModelsRequest,
    ListModelsResponse,
    UpdateModelRequest,
    DeleteModelRequest,
    ExportModelRequest,
    ExportModelOperationMetadata,
    ExportModelResponse,
    GetModelEvaluationRequest,
    ListModelEvaluationsRequest,
    ListModelEvaluationsResponse,
    GetModelEvaluationSliceRequest,
    ListModelEvaluationSlicesRequest,
    ListModelEvaluationSlicesResponse,
)
from .prediction_service import (
    PredictRequest,
    PredictResponse,
    ExplainRequest,
    ExplainResponse,
)
from .data_labeling_job import (
    DataLabelingJob,
    ActiveLearningConfig,
    SampleConfig,
    TrainingConfig,
)
from .job_service import (
    CreateCustomJobRequest,
    GetCustomJobRequest,
    ListCustomJobsRequest,
    ListCustomJobsResponse,
    DeleteCustomJobRequest,
    CancelCustomJobRequest,
    CreateDataLabelingJobRequest,
    GetDataLabelingJobRequest,
    ListDataLabelingJobsRequest,
    ListDataLabelingJobsResponse,
    DeleteDataLabelingJobRequest,
    CancelDataLabelingJobRequest,
    CreateHyperparameterTuningJobRequest,
    GetHyperparameterTuningJobRequest,
    ListHyperparameterTuningJobsRequest,
    ListHyperparameterTuningJobsResponse,
    DeleteHyperparameterTuningJobRequest,
    CancelHyperparameterTuningJobRequest,
    CreateBatchPredictionJobRequest,
    GetBatchPredictionJobRequest,
    ListBatchPredictionJobsRequest,
    ListBatchPredictionJobsResponse,
    DeleteBatchPredictionJobRequest,
    CancelBatchPredictionJobRequest,
)


__all__ = (
    "UserActionReference",
    "GcsSource",
    "GcsDestination",
    "BigQuerySource",
    "BigQueryDestination",
    "ContainerRegistryDestination",
    "EnvVar",
    "MachineSpec",
    "DedicatedResources",
    "AutomaticResources",
    "BatchDedicatedResources",
    "ResourcesConsumed",
    "CustomJob",
    "CustomJobSpec",
    "WorkerPoolSpec",
    "ContainerSpec",
    "PythonPackageSpec",
    "Scheduling",
    "Trial",
    "StudySpec",
    "Measurement",
    "HyperparameterTuningJob",
    "ManualBatchTuningParameters",
    "Dataset",
    "ImportDataConfig",
    "ExportDataConfig",
    "DeployedModelRef",
    "ExplanationMetadata",
    "Explanation",
    "ModelExplanation",
    "Attribution",
    "ExplanationSpec",
    "ExplanationParameters",
    "SampledShapleyAttribution",
    "Model",
    "PredictSchemata",
    "ModelContainerSpec",
    "Port",
    "TrainingPipeline",
    "InputDataConfig",
    "FractionSplit",
    "FilterSplit",
    "PredefinedSplit",
    "TimestampSplit",
    "CreateTrainingPipelineRequest",
    "GetTrainingPipelineRequest",
    "ListTrainingPipelinesRequest",
    "ListTrainingPipelinesResponse",
    "DeleteTrainingPipelineRequest",
    "CancelTrainingPipelineRequest",
    "GenericOperationMetadata",
    "DeleteOperationMetadata",
    "SpecialistPool",
    "CreateSpecialistPoolRequest",
    "CreateSpecialistPoolOperationMetadata",
    "GetSpecialistPoolRequest",
    "ListSpecialistPoolsRequest",
    "ListSpecialistPoolsResponse",
    "DeleteSpecialistPoolRequest",
    "UpdateSpecialistPoolRequest",
    "UpdateSpecialistPoolOperationMetadata",
    "Endpoint",
    "DeployedModel",
    "DataItem",
    "Annotation",
    "AnnotationSpec",
    "CreateDatasetRequest",
    "CreateDatasetOperationMetadata",
    "GetDatasetRequest",
    "UpdateDatasetRequest",
    "ListDatasetsRequest",
    "ListDatasetsResponse",
    "DeleteDatasetRequest",
    "ImportDataRequest",
    "ImportDataResponse",
    "ImportDataOperationMetadata",
    "ExportDataRequest",
    "ExportDataResponse",
    "ExportDataOperationMetadata",
    "ListDataItemsRequest",
    "ListDataItemsResponse",
    "GetAnnotationSpecRequest",
    "ListAnnotationsRequest",
    "ListAnnotationsResponse",
    "CreateEndpointRequest",
    "CreateEndpointOperationMetadata",
    "GetEndpointRequest",
    "ListEndpointsRequest",
    "ListEndpointsResponse",
    "UpdateEndpointRequest",
    "DeleteEndpointRequest",
    "DeployModelRequest",
    "DeployModelResponse",
    "DeployModelOperationMetadata",
    "UndeployModelRequest",
    "UndeployModelResponse",
    "UndeployModelOperationMetadata",
    "ModelEvaluation",
    "CompletionStats",
    "BatchPredictionJob",
    "ModelEvaluationSlice",
    "UploadModelRequest",
    "UploadModelOperationMetadata",
    "UploadModelResponse",
    "GetModelRequest",
    "ListModelsRequest",
    "ListModelsResponse",
    "UpdateModelRequest",
    "DeleteModelRequest",
    "ExportModelRequest",
    "ExportModelOperationMetadata",
    "ExportModelResponse",
    "GetModelEvaluationRequest",
    "ListModelEvaluationsRequest",
    "ListModelEvaluationsResponse",
    "GetModelEvaluationSliceRequest",
    "ListModelEvaluationSlicesRequest",
    "ListModelEvaluationSlicesResponse",
    "PredictRequest",
    "PredictResponse",
    "ExplainRequest",
    "ExplainResponse",
    "DataLabelingJob",
    "ActiveLearningConfig",
    "SampleConfig",
    "TrainingConfig",
    "CreateCustomJobRequest",
    "GetCustomJobRequest",
    "ListCustomJobsRequest",
    "ListCustomJobsResponse",
    "DeleteCustomJobRequest",
    "CancelCustomJobRequest",
    "CreateDataLabelingJobRequest",
    "GetDataLabelingJobRequest",
    "ListDataLabelingJobsRequest",
    "ListDataLabelingJobsResponse",
    "DeleteDataLabelingJobRequest",
    "CancelDataLabelingJobRequest",
    "CreateHyperparameterTuningJobRequest",
    "GetHyperparameterTuningJobRequest",
    "ListHyperparameterTuningJobsRequest",
    "ListHyperparameterTuningJobsResponse",
    "DeleteHyperparameterTuningJobRequest",
    "CancelHyperparameterTuningJobRequest",
    "CreateBatchPredictionJobRequest",
    "GetBatchPredictionJobRequest",
    "ListBatchPredictionJobsRequest",
    "ListBatchPredictionJobsResponse",
    "DeleteBatchPredictionJobRequest",
    "CancelBatchPredictionJobRequest",
)
