# -*- coding: utf-8 -*-
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from .annotation import Annotation
from .annotation_spec import AnnotationSpec
from .batch_prediction_job import BatchPredictionJob
from .completion_stats import CompletionStats
from .custom_job import (
    ContainerSpec,
    CustomJob,
    CustomJobSpec,
    PythonPackageSpec,
    Scheduling,
    WorkerPoolSpec,
)
from .data_item import DataItem
from .data_labeling_job import (
    ActiveLearningConfig,
    DataLabelingJob,
    SampleConfig,
    TrainingConfig,
)
from .dataset import (
    Dataset,
    ExportDataConfig,
    ImportDataConfig,
)
from .dataset_service import (
    CreateDatasetOperationMetadata,
    CreateDatasetRequest,
    DeleteDatasetRequest,
    ExportDataOperationMetadata,
    ExportDataRequest,
    ExportDataResponse,
    GetAnnotationSpecRequest,
    GetDatasetRequest,
    ImportDataOperationMetadata,
    ImportDataRequest,
    ImportDataResponse,
    ListAnnotationsRequest,
    ListAnnotationsResponse,
    ListDataItemsRequest,
    ListDataItemsResponse,
    ListDatasetsRequest,
    ListDatasetsResponse,
    UpdateDatasetRequest,
)
from .deployed_model_ref import DeployedModelRef
from .encryption_spec import EncryptionSpec
from .endpoint import (
    DeployedModel,
    Endpoint,
)
from .endpoint_service import (
    CreateEndpointOperationMetadata,
    CreateEndpointRequest,
    DeleteEndpointRequest,
    DeployModelOperationMetadata,
    DeployModelRequest,
    DeployModelResponse,
    GetEndpointRequest,
    ListEndpointsRequest,
    ListEndpointsResponse,
    UndeployModelOperationMetadata,
    UndeployModelRequest,
    UndeployModelResponse,
    UpdateEndpointRequest,
)
from .env_var import EnvVar
from .hyperparameter_tuning_job import HyperparameterTuningJob
from .io import (
    BigQueryDestination,
    BigQuerySource,
    ContainerRegistryDestination,
    GcsDestination,
    GcsSource,
)
from .job_service import (
    CancelBatchPredictionJobRequest,
    CancelCustomJobRequest,
    CancelDataLabelingJobRequest,
    CancelHyperparameterTuningJobRequest,
    CreateBatchPredictionJobRequest,
    CreateCustomJobRequest,
    CreateDataLabelingJobRequest,
    CreateHyperparameterTuningJobRequest,
    DeleteBatchPredictionJobRequest,
    DeleteCustomJobRequest,
    DeleteDataLabelingJobRequest,
    DeleteHyperparameterTuningJobRequest,
    GetBatchPredictionJobRequest,
    GetCustomJobRequest,
    GetDataLabelingJobRequest,
    GetHyperparameterTuningJobRequest,
    ListBatchPredictionJobsRequest,
    ListBatchPredictionJobsResponse,
    ListCustomJobsRequest,
    ListCustomJobsResponse,
    ListDataLabelingJobsRequest,
    ListDataLabelingJobsResponse,
    ListHyperparameterTuningJobsRequest,
    ListHyperparameterTuningJobsResponse,
)
from .machine_resources import (
    AutomaticResources,
    BatchDedicatedResources,
    DedicatedResources,
    DiskSpec,
    MachineSpec,
    ResourcesConsumed,
)
from .manual_batch_tuning_parameters import ManualBatchTuningParameters
from .migratable_resource import MigratableResource
from .migration_service import (
    BatchMigrateResourcesOperationMetadata,
    BatchMigrateResourcesRequest,
    BatchMigrateResourcesResponse,
    MigrateResourceRequest,
    MigrateResourceResponse,
    SearchMigratableResourcesRequest,
    SearchMigratableResourcesResponse,
)
from .model import (
    Model,
    ModelContainerSpec,
    Port,
    PredictSchemata,
)
from .model_evaluation import ModelEvaluation
from .model_evaluation_slice import ModelEvaluationSlice
from .model_service import (
    DeleteModelRequest,
    ExportModelOperationMetadata,
    ExportModelRequest,
    ExportModelResponse,
    GetModelEvaluationRequest,
    GetModelEvaluationSliceRequest,
    GetModelRequest,
    ListModelEvaluationSlicesRequest,
    ListModelEvaluationSlicesResponse,
    ListModelEvaluationsRequest,
    ListModelEvaluationsResponse,
    ListModelsRequest,
    ListModelsResponse,
    UpdateModelRequest,
    UploadModelOperationMetadata,
    UploadModelRequest,
    UploadModelResponse,
)
from .operation import (
    DeleteOperationMetadata,
    GenericOperationMetadata,
)
from .pipeline_service import (
    CancelTrainingPipelineRequest,
    CreateTrainingPipelineRequest,
    DeleteTrainingPipelineRequest,
    GetTrainingPipelineRequest,
    ListTrainingPipelinesRequest,
    ListTrainingPipelinesResponse,
)
from .prediction_service import (
    PredictRequest,
    PredictResponse,
)
from .specialist_pool import SpecialistPool
from .specialist_pool_service import (
    CreateSpecialistPoolOperationMetadata,
    CreateSpecialistPoolRequest,
    DeleteSpecialistPoolRequest,
    GetSpecialistPoolRequest,
    ListSpecialistPoolsRequest,
    ListSpecialistPoolsResponse,
    UpdateSpecialistPoolOperationMetadata,
    UpdateSpecialistPoolRequest,
)
from .study import (
    Measurement,
    StudySpec,
    Trial,
)
from .training_pipeline import (
    FilterSplit,
    FractionSplit,
    InputDataConfig,
    PredefinedSplit,
    TimestampSplit,
    TrainingPipeline,
)
from .user_action_reference import UserActionReference

__all__ = (
    "AcceleratorType",
    "Annotation",
    "AnnotationSpec",
    "BatchPredictionJob",
    "CompletionStats",
    "ContainerSpec",
    "CustomJob",
    "CustomJobSpec",
    "PythonPackageSpec",
    "Scheduling",
    "WorkerPoolSpec",
    "DataItem",
    "ActiveLearningConfig",
    "DataLabelingJob",
    "SampleConfig",
    "TrainingConfig",
    "Dataset",
    "ExportDataConfig",
    "ImportDataConfig",
    "CreateDatasetOperationMetadata",
    "CreateDatasetRequest",
    "DeleteDatasetRequest",
    "ExportDataOperationMetadata",
    "ExportDataRequest",
    "ExportDataResponse",
    "GetAnnotationSpecRequest",
    "GetDatasetRequest",
    "ImportDataOperationMetadata",
    "ImportDataRequest",
    "ImportDataResponse",
    "ListAnnotationsRequest",
    "ListAnnotationsResponse",
    "ListDataItemsRequest",
    "ListDataItemsResponse",
    "ListDatasetsRequest",
    "ListDatasetsResponse",
    "UpdateDatasetRequest",
    "DeployedModelRef",
    "EncryptionSpec",
    "DeployedModel",
    "Endpoint",
    "CreateEndpointOperationMetadata",
    "CreateEndpointRequest",
    "DeleteEndpointRequest",
    "DeployModelOperationMetadata",
    "DeployModelRequest",
    "DeployModelResponse",
    "GetEndpointRequest",
    "ListEndpointsRequest",
    "ListEndpointsResponse",
    "UndeployModelOperationMetadata",
    "UndeployModelRequest",
    "UndeployModelResponse",
    "UpdateEndpointRequest",
    "EnvVar",
    "HyperparameterTuningJob",
    "BigQueryDestination",
    "BigQuerySource",
    "ContainerRegistryDestination",
    "GcsDestination",
    "GcsSource",
    "CancelBatchPredictionJobRequest",
    "CancelCustomJobRequest",
    "CancelDataLabelingJobRequest",
    "CancelHyperparameterTuningJobRequest",
    "CreateBatchPredictionJobRequest",
    "CreateCustomJobRequest",
    "CreateDataLabelingJobRequest",
    "CreateHyperparameterTuningJobRequest",
    "DeleteBatchPredictionJobRequest",
    "DeleteCustomJobRequest",
    "DeleteDataLabelingJobRequest",
    "DeleteHyperparameterTuningJobRequest",
    "GetBatchPredictionJobRequest",
    "GetCustomJobRequest",
    "GetDataLabelingJobRequest",
    "GetHyperparameterTuningJobRequest",
    "ListBatchPredictionJobsRequest",
    "ListBatchPredictionJobsResponse",
    "ListCustomJobsRequest",
    "ListCustomJobsResponse",
    "ListDataLabelingJobsRequest",
    "ListDataLabelingJobsResponse",
    "ListHyperparameterTuningJobsRequest",
    "ListHyperparameterTuningJobsResponse",
    "JobState",
    "AutomaticResources",
    "BatchDedicatedResources",
    "DedicatedResources",
    "DiskSpec",
    "MachineSpec",
    "ResourcesConsumed",
    "ManualBatchTuningParameters",
    "MigratableResource",
    "BatchMigrateResourcesOperationMetadata",
    "BatchMigrateResourcesRequest",
    "BatchMigrateResourcesResponse",
    "MigrateResourceRequest",
    "MigrateResourceResponse",
    "SearchMigratableResourcesRequest",
    "SearchMigratableResourcesResponse",
    "Model",
    "ModelContainerSpec",
    "Port",
    "PredictSchemata",
    "ModelEvaluation",
    "ModelEvaluationSlice",
    "DeleteModelRequest",
    "ExportModelOperationMetadata",
    "ExportModelRequest",
    "ExportModelResponse",
    "GetModelEvaluationRequest",
    "GetModelEvaluationSliceRequest",
    "GetModelRequest",
    "ListModelEvaluationSlicesRequest",
    "ListModelEvaluationSlicesResponse",
    "ListModelEvaluationsRequest",
    "ListModelEvaluationsResponse",
    "ListModelsRequest",
    "ListModelsResponse",
    "UpdateModelRequest",
    "UploadModelOperationMetadata",
    "UploadModelRequest",
    "UploadModelResponse",
    "DeleteOperationMetadata",
    "GenericOperationMetadata",
    "CancelTrainingPipelineRequest",
    "CreateTrainingPipelineRequest",
    "DeleteTrainingPipelineRequest",
    "GetTrainingPipelineRequest",
    "ListTrainingPipelinesRequest",
    "ListTrainingPipelinesResponse",
    "PipelineState",
    "PredictRequest",
    "PredictResponse",
    "SpecialistPool",
    "CreateSpecialistPoolOperationMetadata",
    "CreateSpecialistPoolRequest",
    "DeleteSpecialistPoolRequest",
    "GetSpecialistPoolRequest",
    "ListSpecialistPoolsRequest",
    "ListSpecialistPoolsResponse",
    "UpdateSpecialistPoolOperationMetadata",
    "UpdateSpecialistPoolRequest",
    "Measurement",
    "StudySpec",
    "Trial",
    "FilterSplit",
    "FractionSplit",
    "InputDataConfig",
    "PredefinedSplit",
    "TimestampSplit",
    "TrainingPipeline",
    "UserActionReference",
)
