# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import logging
import typing
from typing import Optional, Union
from google.genai import _common
from pydantic import Field
from typing_extensions import TypedDict

logger = logging.getLogger('google_genai.types')

T = typing.TypeVar('T', bound='GenerateContentResponse')


class HttpOptions(_common.BaseModel):
  """HTTP options to be used in each of the requests."""

  base_url: Optional[str] = Field(
      default=None,
      description="""The base URL for the AI platform service endpoint.""",
  )
  api_version: Optional[str] = Field(
      default=None, description="""Specifies the version of the API to use."""
  )
  headers: Optional[dict[str, str]] = Field(
      default=None,
      description="""Additional HTTP headers to be sent with the request.""",
  )
  timeout: Optional[int] = Field(
      default=None, description="""Timeout for the request in milliseconds."""
  )


class HttpOptionsDict(TypedDict, total=False):
  """HTTP options to be used in each of the requests."""

  base_url: Optional[str]
  """The base URL for the AI platform service endpoint."""

  api_version: Optional[str]
  """Specifies the version of the API to use."""

  headers: Optional[dict[str, str]]
  """Additional HTTP headers to be sent with the request."""

  timeout: Optional[int]
  """Timeout for the request in milliseconds."""


HttpOptionsOrDict = Union[HttpOptions, HttpOptionsDict]


class GetAgentEngineConfig(_common.BaseModel):
  """Optional configuration for agent engine creation."""

  http_options: Optional[HttpOptions] = Field(
      default=None, description="""Used to override HTTP request options."""
  )


class GetAgentEngineConfigDict(TypedDict, total=False):
  """Optional configuration for agent engine creation."""

  http_options: Optional[HttpOptionsDict]
  """Used to override HTTP request options."""


GetAgentEngineConfigOrDict = Union[
    GetAgentEngineConfig, GetAgentEngineConfigDict
]


class _GetAgentEngineParameters(_common.BaseModel):
  """Parameters for creating an agent engine."""

  name: Optional[str] = Field(
      default=None, description="""Name of the agent engine."""
  )
  config: Optional[GetAgentEngineConfig] = Field(
      default=None,
      description="""Configuration that contains optional parameters.
      """,
  )


class _GetAgentEngineParametersDict(TypedDict, total=False):
  """Parameters for creating an agent engine."""

  name: Optional[str]
  """Name of the agent engine."""

  config: Optional[GetAgentEngineConfigDict]
  """Configuration that contains optional parameters.
      """


_GetAgentEngineParametersOrDict = Union[
    _GetAgentEngineParameters, _GetAgentEngineParametersDict
]


class Agent(_common.BaseModel):

  name: Optional[str] = Field(
      default=None,
      description="""Name of the agent engine.
      """,
  )
  model: Optional[str] = Field(
      default=None,
      description="""Name of the model used by the agent engine.
      """,
  )


class AgentDict(TypedDict, total=False):

  name: Optional[str]
  """Name of the agent engine.
      """

  model: Optional[str]
  """Name of the model used by the agent engine.
      """


AgentOrDict = Union[Agent, AgentDict]
