# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import functools
import importlib
import json
import logging
import typing
from typing import Any, AsyncIterator, Iterator, Optional, Union
from urllib.parse import urlencode

from google.genai import _api_module
from google.genai import _common
from google.genai._common import get_value_by_path as getv
from google.genai._common import set_value_by_path as setv
from google.genai.pagers import AsyncPager, Pager

from . import _agent_engines_utils
from . import types

if typing.TYPE_CHECKING:
    from . import feedback_contexts as feedback_contexts_module

    _ = feedback_contexts_module


logger = logging.getLogger("agentplatform_genai.feedbackentries")

logger.setLevel(logging.INFO)


def _CreateRuntimeFeedbackEntryConfig_to_vertex(
    from_object: Union[dict[str, Any], object],
    parent_object: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    to_object: dict[str, Any] = {}

    if getv(from_object, ["feedback_labels"]) is not None:
        setv(parent_object, ["feedbackLabels"], getv(from_object, ["feedback_labels"]))

    if getv(from_object, ["feedback_text"]) is not None:
        setv(parent_object, ["feedbackText"], getv(from_object, ["feedback_text"]))

    if getv(from_object, ["user_id"]) is not None:
        setv(parent_object, ["userId"], getv(from_object, ["user_id"]))

    if getv(from_object, ["source"]) is not None:
        setv(parent_object, ["source"], getv(from_object, ["source"]))

    if getv(from_object, ["custom_metadata"]) is not None:
        setv(parent_object, ["customMetadata"], getv(from_object, ["custom_metadata"]))

    return to_object


def _CreateRuntimeFeedbackEntryRequestParameters_to_vertex(
    from_object: Union[dict[str, Any], object],
    parent_object: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    to_object: dict[str, Any] = {}
    if getv(from_object, ["name"]) is not None:
        setv(to_object, ["_url", "parent"], getv(from_object, ["name"]))

    if getv(from_object, ["feedback_type"]) is not None:
        setv(to_object, ["feedbackType"], getv(from_object, ["feedback_type"]))

    if getv(from_object, ["session_id"]) is not None:
        setv(to_object, ["sessionId"], getv(from_object, ["session_id"]))

    if getv(from_object, ["event_id"]) is not None:
        setv(to_object, ["eventId"], getv(from_object, ["event_id"]))

    if getv(from_object, ["config"]) is not None:
        _CreateRuntimeFeedbackEntryConfig_to_vertex(
            getv(from_object, ["config"]), to_object
        )

    return to_object


def _DeleteRuntimeFeedbackEntryRequestParameters_to_vertex(
    from_object: Union[dict[str, Any], object],
    parent_object: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    to_object: dict[str, Any] = {}
    if getv(from_object, ["name"]) is not None:
        setv(to_object, ["_url", "name"], getv(from_object, ["name"]))

    return to_object


def _GetRuntimeFeedbackOperationParameters_to_vertex(
    from_object: Union[dict[str, Any], object],
    parent_object: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    to_object: dict[str, Any] = {}
    if getv(from_object, ["operation_name"]) is not None:
        setv(
            to_object, ["_url", "operationName"], getv(from_object, ["operation_name"])
        )

    return to_object


def _GetRuntimeFeedbackRequestParameters_to_vertex(
    from_object: Union[dict[str, Any], object],
    parent_object: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    to_object: dict[str, Any] = {}
    if getv(from_object, ["name"]) is not None:
        setv(to_object, ["_url", "name"], getv(from_object, ["name"]))

    return to_object


def _ListRuntimeFeedbackEntriesConfig_to_vertex(
    from_object: Union[dict[str, Any], object],
    parent_object: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    to_object: dict[str, Any] = {}

    if getv(from_object, ["page_size"]) is not None:
        setv(parent_object, ["_query", "pageSize"], getv(from_object, ["page_size"]))

    if getv(from_object, ["page_token"]) is not None:
        setv(parent_object, ["_query", "pageToken"], getv(from_object, ["page_token"]))

    if getv(from_object, ["filter"]) is not None:
        setv(parent_object, ["_query", "filter"], getv(from_object, ["filter"]))

    if getv(from_object, ["order_by"]) is not None:
        setv(parent_object, ["_query", "orderBy"], getv(from_object, ["order_by"]))

    return to_object


def _ListRuntimeFeedbackEntriesRequestParameters_to_vertex(
    from_object: Union[dict[str, Any], object],
    parent_object: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    to_object: dict[str, Any] = {}
    if getv(from_object, ["parent"]) is not None:
        setv(to_object, ["_url", "parent"], getv(from_object, ["parent"]))

    if getv(from_object, ["config"]) is not None:
        _ListRuntimeFeedbackEntriesConfig_to_vertex(
            getv(from_object, ["config"]), to_object
        )

    return to_object


def _UpdateRuntimeFeedbackEntryConfig_to_vertex(
    from_object: Union[dict[str, Any], object],
    parent_object: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    to_object: dict[str, Any] = {}

    if getv(from_object, ["update_mask"]) is not None:
        setv(
            parent_object, ["_query", "updateMask"], getv(from_object, ["update_mask"])
        )

    if getv(from_object, ["feedback_type"]) is not None:
        setv(parent_object, ["feedbackType"], getv(from_object, ["feedback_type"]))

    if getv(from_object, ["session_id"]) is not None:
        setv(parent_object, ["sessionId"], getv(from_object, ["session_id"]))

    if getv(from_object, ["event_id"]) is not None:
        setv(parent_object, ["eventId"], getv(from_object, ["event_id"]))

    if getv(from_object, ["feedback_labels"]) is not None:
        setv(parent_object, ["feedbackLabels"], getv(from_object, ["feedback_labels"]))

    if getv(from_object, ["feedback_text"]) is not None:
        setv(parent_object, ["feedbackText"], getv(from_object, ["feedback_text"]))

    if getv(from_object, ["user_id"]) is not None:
        setv(parent_object, ["userId"], getv(from_object, ["user_id"]))

    if getv(from_object, ["source"]) is not None:
        setv(parent_object, ["source"], getv(from_object, ["source"]))

    if getv(from_object, ["custom_metadata"]) is not None:
        setv(parent_object, ["customMetadata"], getv(from_object, ["custom_metadata"]))

    return to_object


def _UpdateRuntimeFeedbackEntryRequestParameters_to_vertex(
    from_object: Union[dict[str, Any], object],
    parent_object: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    to_object: dict[str, Any] = {}
    if getv(from_object, ["name"]) is not None:
        setv(to_object, ["_url", "name"], getv(from_object, ["name"]))

    if getv(from_object, ["config"]) is not None:
        _UpdateRuntimeFeedbackEntryConfig_to_vertex(
            getv(from_object, ["config"]), to_object
        )

    return to_object


class FeedbackEntries(_api_module.BaseModule):

    def _create(
        self,
        *,
        name: str,
        feedback_type: types.FeedbackType,
        session_id: str,
        event_id: str,
        config: Optional[types.CreateRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.RuntimeFeedbackEntryOperation:
        parameter_model = types._CreateRuntimeFeedbackEntryRequestParameters(
            name=name,
            feedback_type=feedback_type,
            session_id=session_id,
            event_id=event_id,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _CreateRuntimeFeedbackEntryRequestParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{parent}/feedbackEntries".format_map(request_url_dict)
            else:
                path = "{parent}/feedbackEntries"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = self._api_client.request("post", path, request_dict, http_options)

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.RuntimeFeedbackEntryOperation._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    def _delete(
        self,
        *,
        name: str,
        config: Optional[types.DeleteRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.DeleteRuntimeFeedbackEntryOperation:
        parameter_model = types._DeleteRuntimeFeedbackEntryRequestParameters(
            name=name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _DeleteRuntimeFeedbackEntryRequestParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{name}".format_map(request_url_dict)
            else:
                path = "{name}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = self._api_client.request("delete", path, request_dict, http_options)

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.DeleteRuntimeFeedbackEntryOperation._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    def get(
        self,
        *,
        name: str,
        config: Optional[types.GetRuntimeFeedbackConfigOrDict] = None,
    ) -> types.FeedbackEntry:
        """
        Gets a Runtime Feedback Entry.

        Args:
            name (str): Required. The name of the Feedback Entry to retrieve. Format:
                `projects/{project}/locations/{location}/reasoningEngines/{resource_id}/feedbackEntries/{feedback_entry_id}`.
            config (GetRuntimeFeedbackConfig):
                Optional. The configuration for getting the Feedback Entry.

        Returns:
            FeedbackEntry: The requested Feedback Entry.

        """

        parameter_model = types._GetRuntimeFeedbackRequestParameters(
            name=name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _GetRuntimeFeedbackRequestParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{name}".format_map(request_url_dict)
            else:
                path = "{name}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = self._api_client.request("get", path, request_dict, http_options)

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.FeedbackEntry._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    def _list(
        self,
        *,
        parent: str,
        config: Optional[types.ListRuntimeFeedbackEntriesConfigOrDict] = None,
    ) -> types.ListRuntimeFeedbackEntriesResponse:
        parameter_model = types._ListRuntimeFeedbackEntriesRequestParameters(
            parent=parent,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _ListRuntimeFeedbackEntriesRequestParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{parent}/feedbackEntries".format_map(request_url_dict)
            else:
                path = "{parent}/feedbackEntries"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = self._api_client.request("get", path, request_dict, http_options)

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.ListRuntimeFeedbackEntriesResponse._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    def _update(
        self,
        *,
        name: str,
        config: Optional[types.UpdateRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.RuntimeFeedbackEntryOperation:
        """
        Updates a Feedback Entry.

        Args:
            name (str): Required. Name of the Feedback Entry to update. Format:
                `projects/{project}/locations/{location}/reasoningEngines/{resource_id}/feedbackEntries/{feedback_entry_id}`.
            feedback_type (shared.FeedbackType): Optional. The type of feedback provided.
            config (UpdateRuntimeFeedbackEntryConfig): Optional. The configuration for updating the Feedback Entry.

        Returns:
            RuntimeFeedbackEntryOperation: Operation for updating a Feedback Entry.

        """

        parameter_model = types._UpdateRuntimeFeedbackEntryRequestParameters(
            name=name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _UpdateRuntimeFeedbackEntryRequestParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{name}".format_map(request_url_dict)
            else:
                path = "{name}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = self._api_client.request("patch", path, request_dict, http_options)

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.RuntimeFeedbackEntryOperation._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    def _get_feedback_entry_operation(
        self,
        *,
        operation_name: str,
        config: Optional[types.GetRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.RuntimeFeedbackEntryOperation:
        parameter_model = types._GetRuntimeFeedbackOperationParameters(
            operation_name=operation_name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _GetRuntimeFeedbackOperationParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{operationName}".format_map(request_url_dict)
            else:
                path = "{operationName}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = self._api_client.request("get", path, request_dict, http_options)

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.RuntimeFeedbackEntryOperation._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    def _get_delete_feedback_entry_operation(
        self,
        *,
        operation_name: str,
        config: Optional[types.GetRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.DeleteRuntimeFeedbackEntryOperation:
        parameter_model = types._GetRuntimeFeedbackOperationParameters(
            operation_name=operation_name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _GetRuntimeFeedbackOperationParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{operationName}".format_map(request_url_dict)
            else:
                path = "{operationName}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = self._api_client.request("get", path, request_dict, http_options)

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.DeleteRuntimeFeedbackEntryOperation._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    _feedback_contexts = None

    @property
    def feedback_contexts(self) -> "feedback_contexts_module.FeedbackContexts":
        if self._feedback_contexts is None:
            try:
                # We need to lazy load the feedback_contexts module to handle the
                # possibility of ImportError when dependencies are not installed.
                self._feedback_contexts = importlib.import_module(
                    ".feedback_contexts", __package__
                )
            except ImportError as e:
                raise ImportError(
                    "The 'feedback_entries.feedback_contexts' module requires additional "
                    "packages. Please install them using pip install "
                    "google-cloud-aiplatform[agent_engines]"
                ) from e
        return self._feedback_contexts.FeedbackContexts(
            self._api_client
        )  # type: ignore[no-any-return]

    def create(
        self,
        *,
        name: str,
        feedback_type: str,
        session_id: str,
        event_id: str,
        config: Optional[types.CreateRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.RuntimeFeedbackEntryOperation:
        """Creates a new Feedback Entry in the Runtime.

        Args:
            name (str): Required. Resource name of the Runtime to create the
                Feedback Entry in. Format:
                `projects/{project}/locations/{location}/reasoningEngines/{resource_id}`.
            feedback_type (FeedbackType): Required. The type of feedback provided.
            session_id (str): Required. The ID of the session to which the feedback
                relates to.
            event_id (str): Required. The ID of the event to which the feedback
                relates to.
            config (CreateRuntimeFeedbackEntryConfig):
                Optional. Additional configurations for creating the Feedback Entry.

        Returns:
            RuntimeFeedbackEntryOperation: The operation for creating the
                Feedback Entry.
        """
        if config is None:
            config = types.CreateRuntimeFeedbackEntryConfig()
        elif isinstance(config, dict):
            config = types.CreateRuntimeFeedbackEntryConfig.model_validate(config)
        operation = self._create(
            name=name,
            session_id=session_id,
            event_id=event_id,
            feedback_type=feedback_type,
            config=config,
        )
        if config.wait_for_completion:
            if not operation.done:
                operation = _agent_engines_utils._await_operation(
                    operation_name=operation.name,
                    get_operation_fn=self._get_feedback_entry_operation,
                    poll_interval_seconds=0.5,
                )
            if operation.error:
                raise RuntimeError(
                    f"Failed to create Feedback Entry: {operation.error}"
                )
        return operation

    def list(
        self,
        *,
        parent: str,
        config: Optional[types.ListRuntimeFeedbackEntriesConfigOrDict] = None,
    ) -> Iterator[types.FeedbackEntry]:
        """
    Lists Feedback Entries in the Runtime.

    Args:
        parent (str): Required. Resource name of the Runtime to list the
            Feedback Entries from. Format:
            `projects/{project}/locations/{location}/reasoningEngines/{resource_id}`.
        config (ListRuntimeFeedbackEntriesConfig):
            Optional. The configuration for listing Feedback Entries.

    Returns:
        Iterable[FeedbackEntry]: A pager of Feedback Entries.
    """,

        return Pager(
            "feedback_entries",
            functools.partial(self._list, parent=parent),
            self._list(parent=parent, config=config),
            config,
        )

    def update(
        self,
        *,
        name: str,
        config: Optional[types.UpdateRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.RuntimeFeedbackEntryOperation:
        """Updates a Feedback Entry in the Runtime.

        Args:
            name (str): Required. Name of the Feedback Entry. Format:
                `projects/{project}/locations/{location}/reasoningEngines/{resource_id}/feedbackEntries/{feedback_entry_id}`.
            feedback_type (str): Optional. The type of feedback provided.
            config (UpdateRuntimeFeedbackEntryConfig):
                Optional. Additional configurations for updating the Feedback Entry.

        Returns:
            RuntimeFeedbackEntryOperation: The operation for updating
                the Feedback Entry.
        """
        if config is None:
            config = types.UpdateRuntimeFeedbackEntryConfig()
        elif isinstance(config, dict):
            config = types.UpdateRuntimeFeedbackEntryConfig.model_validate(config)
        operation = self._update(
            name=name,
            config=config,
        )
        if config.wait_for_completion:
            if not operation.done:
                operation = _agent_engines_utils._await_operation(
                    operation_name=operation.name,
                    get_operation_fn=self._get_feedback_entry_operation,
                    poll_interval_seconds=0.5,
                )
            if operation.error:
                raise RuntimeError(
                    f"Failed to update Feedback Entry: {operation.error}"
                )
        return operation

    def delete(
        self,
        *,
        name: str,
        config: Optional[types.DeleteRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.DeleteRuntimeFeedbackEntryOperation:
        """Deletes a Feedback Entry from the Runtime.

        Args:
            name (str): Required. Name of the Feedback Entry to delete. Format:
                `projects/{project}/locations/{location}/reasoningEngines/{resource_id}/feedbackEntries/{feedback_entry_id}`.
            config (DeleteRuntimeFeedbackEntryConfig):
                Optional. The configuration for deleting the Feedback Entry.

        Returns:
            DeleteRuntimeFeedbackEntryOperation: The operation for deleting
                the Feedback Entry.
        """
        if config is None:
            config = types.DeleteRuntimeFeedbackEntryConfig()
        elif isinstance(config, dict):
            config = types.DeleteRuntimeFeedbackEntryConfig.model_validate(config)
        operation = self._delete(
            name=name,
            config=config,
        )
        if config.wait_for_completion:
            if not operation.done:
                operation = _agent_engines_utils._await_operation(
                    operation_name=operation.name,
                    get_operation_fn=self._get_delete_feedback_entry_operation,
                    poll_interval_seconds=0.5,
                )
            if operation.error:
                raise RuntimeError(
                    f"Failed to delete Feedback Entry: {operation.error}"
                )
        return operation


class AsyncFeedbackEntries(_api_module.BaseModule):

    async def _create(
        self,
        *,
        name: str,
        feedback_type: types.FeedbackType,
        session_id: str,
        event_id: str,
        config: Optional[types.CreateRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.RuntimeFeedbackEntryOperation:
        parameter_model = types._CreateRuntimeFeedbackEntryRequestParameters(
            name=name,
            feedback_type=feedback_type,
            session_id=session_id,
            event_id=event_id,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _CreateRuntimeFeedbackEntryRequestParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{parent}/feedbackEntries".format_map(request_url_dict)
            else:
                path = "{parent}/feedbackEntries"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = await self._api_client.async_request(
            "post", path, request_dict, http_options
        )

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.RuntimeFeedbackEntryOperation._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    async def _delete(
        self,
        *,
        name: str,
        config: Optional[types.DeleteRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.DeleteRuntimeFeedbackEntryOperation:
        parameter_model = types._DeleteRuntimeFeedbackEntryRequestParameters(
            name=name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _DeleteRuntimeFeedbackEntryRequestParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{name}".format_map(request_url_dict)
            else:
                path = "{name}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = await self._api_client.async_request(
            "delete", path, request_dict, http_options
        )

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.DeleteRuntimeFeedbackEntryOperation._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    async def get(
        self,
        *,
        name: str,
        config: Optional[types.GetRuntimeFeedbackConfigOrDict] = None,
    ) -> types.FeedbackEntry:
        """
        Gets a Runtime Feedback Entry.

        Args:
            name (str): Required. The name of the Feedback Entry to retrieve. Format:
                `projects/{project}/locations/{location}/reasoningEngines/{resource_id}/feedbackEntries/{feedback_entry_id}`.
            config (GetRuntimeFeedbackConfig):
                Optional. The configuration for getting the Feedback Entry.

        Returns:
            FeedbackEntry: The requested Feedback Entry.

        """

        parameter_model = types._GetRuntimeFeedbackRequestParameters(
            name=name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _GetRuntimeFeedbackRequestParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{name}".format_map(request_url_dict)
            else:
                path = "{name}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = await self._api_client.async_request(
            "get", path, request_dict, http_options
        )

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.FeedbackEntry._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    async def _list(
        self,
        *,
        parent: str,
        config: Optional[types.ListRuntimeFeedbackEntriesConfigOrDict] = None,
    ) -> types.ListRuntimeFeedbackEntriesResponse:
        parameter_model = types._ListRuntimeFeedbackEntriesRequestParameters(
            parent=parent,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _ListRuntimeFeedbackEntriesRequestParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{parent}/feedbackEntries".format_map(request_url_dict)
            else:
                path = "{parent}/feedbackEntries"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = await self._api_client.async_request(
            "get", path, request_dict, http_options
        )

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.ListRuntimeFeedbackEntriesResponse._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    async def _update(
        self,
        *,
        name: str,
        config: Optional[types.UpdateRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.RuntimeFeedbackEntryOperation:
        """
        Updates a Feedback Entry.

        Args:
            name (str): Required. Name of the Feedback Entry to update. Format:
                `projects/{project}/locations/{location}/reasoningEngines/{resource_id}/feedbackEntries/{feedback_entry_id}`.
            feedback_type (shared.FeedbackType): Optional. The type of feedback provided.
            config (UpdateRuntimeFeedbackEntryConfig): Optional. The configuration for updating the Feedback Entry.

        Returns:
            RuntimeFeedbackEntryOperation: Operation for updating a Feedback Entry.

        """

        parameter_model = types._UpdateRuntimeFeedbackEntryRequestParameters(
            name=name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _UpdateRuntimeFeedbackEntryRequestParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{name}".format_map(request_url_dict)
            else:
                path = "{name}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = await self._api_client.async_request(
            "patch", path, request_dict, http_options
        )

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.RuntimeFeedbackEntryOperation._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    async def _get_feedback_entry_operation(
        self,
        *,
        operation_name: str,
        config: Optional[types.GetRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.RuntimeFeedbackEntryOperation:
        parameter_model = types._GetRuntimeFeedbackOperationParameters(
            operation_name=operation_name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _GetRuntimeFeedbackOperationParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{operationName}".format_map(request_url_dict)
            else:
                path = "{operationName}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = await self._api_client.async_request(
            "get", path, request_dict, http_options
        )

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.RuntimeFeedbackEntryOperation._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    async def _get_delete_feedback_entry_operation(
        self,
        *,
        operation_name: str,
        config: Optional[types.GetRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.DeleteRuntimeFeedbackEntryOperation:
        parameter_model = types._GetRuntimeFeedbackOperationParameters(
            operation_name=operation_name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
            )
        else:
            request_dict = _GetRuntimeFeedbackOperationParameters_to_vertex(
                parameter_model
            )
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{operationName}".format_map(request_url_dict)
            else:
                path = "{operationName}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = await self._api_client.async_request(
            "get", path, request_dict, http_options
        )

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.DeleteRuntimeFeedbackEntryOperation._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value

    _feedback_contexts = None

    @property
    def feedback_contexts(self) -> "feedback_contexts_module.FeedbackContexts":
        if self._feedback_contexts is None:
            try:
                # We need to lazy load the feedback_contexts module to handle the
                # possibility of ImportError when dependencies are not installed.
                self._feedback_contexts = importlib.import_module(
                    ".feedback_contexts", __package__
                )
            except ImportError as e:
                raise ImportError(
                    "The 'feedback_entries.feedback_contexts' module requires additional "
                    "packages. Please install them using pip install "
                    "google-cloud-aiplatform[agent_engines]"
                ) from e
        return self._feedback_contexts.AsyncFeedbackContexts(
            self._api_client
        )  # type: ignore[no-any-return]

    async def create(
        self,
        *,
        name: str,
        feedback_type: types.FeedbackType,
        session_id: str,
        event_id: str,
        config: Optional[types.CreateRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.RuntimeFeedbackEntryOperation:
        """
        Creates a new Feedback Entry in the Runtime.

        Args:
            name (str): Required. Resource name of the Runtime to create
                the Feedback Entry in. Format:
                `projects/{project}/locations/{location}/reasoningEngines/{resource_id}`.
            feedback_type (FeedbackType): Required. The type of feedback provided.
            session_id (str): Required. The ID of the session to which the feedback
                relates to.
            event_id (str): Required. The ID of the event to which the feedback
                relates to.
            config (CreateRuntimeFeedbackEntryConfig):
                Optional. Additional configurations for creating the Feedback Entry.

        Returns:
            RuntimeFeedbackEntryOperation: The operation for creating the
                Feedback Entry.

        """
        if config is None:
            config = types.CreateRuntimeFeedbackEntryConfig()
        elif isinstance(config, dict):
            config = types.CreateRuntimeFeedbackEntryConfig.model_validate(config)
        operation = await self._create(
            name=name,
            session_id=session_id,
            event_id=event_id,
            feedback_type=feedback_type,
            config=config,
        )
        if config.wait_for_completion:
            if not operation.done:
                operation = await _agent_engines_utils._await_async_operation(
                    operation_name=operation.name,
                    get_operation_fn=self._get_feedback_entry_operation,
                    poll_interval_seconds=0.5,
                )
            if operation.error:
                raise RuntimeError(
                    f"Failed to create Feedback Entry: {operation.error}"
                )
        return operation

    async def list(
        self,
        *,
        parent: str,
        config: Optional[types.ListRuntimeFeedbackEntriesConfigOrDict] = None,
    ) -> AsyncIterator[types.FeedbackEntry]:
        """
    Lists Feedback Entries in the Runtime.

    Args:
        parent (str): Required. Resource name of the Runtime to list the
            Feedback Entries from. Format:
            `projects/{project}/locations/{location}/reasoningEngines/{resource_id}`.
        config (ListRuntimeFeedbackEntriesConfigOrDict):
            Optional. The configuration for listing Feedback Entries.

    Returns:
        AsyncPager[FeedbackEntry]: An async pager of Feedback Entries.
    """,

        return AsyncPager(
            "feedback_entries",
            functools.partial(self._list, parent=parent),
            await self._list(parent=parent, config=config),
            config,
        )

    async def update(
        self,
        *,
        name: str,
        config: Optional[types.UpdateRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.RuntimeFeedbackEntryOperation:
        """Updates a Feedback Entry in the Runtime.

        Args:
            name (str): Required. Name of the Feedback Entry. Format:
                `projects/{project}/locations/{location}/reasoningEngines/{resource_id}/feedbackEntries/{feedback_entry_id}`.
            feedback_type (str): Optional. The type of feedback provided.
            config (UpdateRuntimeFeedbackEntryConfig):
                Optional. Additional configurations for updating the Feedback Entry.

        Returns:
            RuntimeFeedbackEntryOperation: The operation for updating
                the Feedback Entry.
        """
        if config is None:
            config = types.UpdateRuntimeFeedbackEntryConfig()
        elif isinstance(config, dict):
            config = types.UpdateRuntimeFeedbackEntryConfig.model_validate(config)
        operation = await self._update(
            name=name,
            config=config,
        )
        if config.wait_for_completion:
            if not operation.done:
                operation = await _agent_engines_utils._await_async_operation(
                    operation_name=operation.name,
                    get_operation_fn=self._get_feedback_entry_operation,
                    poll_interval_seconds=0.5,
                )
            if operation.error:
                raise RuntimeError(
                    f"Failed to update Feedback Entry: {operation.error}"
                )
        return operation

    async def delete(
        self,
        *,
        name: str,
        config: Optional[types.DeleteRuntimeFeedbackEntryConfigOrDict] = None,
    ) -> types.DeleteRuntimeFeedbackEntryOperation:
        """Deletes a Feedback Entry from the Runtime.

        Args:
            name (str): Required. Name of the Feedback Entry to delete. Format:
                `projects/{project}/locations/{location}/reasoningEngines/{resource_id}/feedbackEntries/{feedback_entry_id}`.
            config (DeleteRuntimeFeedbackEntryConfig):
                Optional. The configuration for deleting the Feedback Entry.

        Returns:
            DeleteRuntimeFeedbackEntryOperation: The operation for deleting
                the Feedback Entry.
        """
        if config is None:
            config = types.DeleteRuntimeFeedbackEntryConfig()
        elif isinstance(config, dict):
            config = types.DeleteRuntimeFeedbackEntryConfig.model_validate(config)
        operation = await self._delete(
            name=name,
            config=config,
        )
        if config.wait_for_completion:
            if not operation.done:
                operation = await _agent_engines_utils._await_async_operation(
                    operation_name=operation.name,
                    get_operation_fn=self._get_delete_feedback_entry_operation,
                    poll_interval_seconds=0.5,
                )
            if operation.error:
                raise RuntimeError(
                    f"Failed to delete Feedback Entry: {operation.error}"
                )
        return operation
