# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Code generated by the Google Gen AI SDK generator DO NOT EDIT.

from typing import Optional, Union
from google.genai import _common
from pydantic import Field
from typing_extensions import TypedDict


class ApplicableGuideline(_common.BaseModel):
    """Applicable guideline for the optimize_prompt method."""

    applicable_guideline: Optional[str] = Field(default=None, description="""""")
    suggested_improvement: Optional[str] = Field(default=None, description="""""")
    text_before_change: Optional[str] = Field(default=None, description="""""")
    text_after_change: Optional[str] = Field(default=None, description="""""")


class ApplicableGuidelineDict(TypedDict, total=False):
    """Applicable guideline for the optimize_prompt method."""

    applicable_guideline: Optional[str]
    """"""

    suggested_improvement: Optional[str]
    """"""

    text_before_change: Optional[str]
    """"""

    text_after_change: Optional[str]
    """"""


ApplicableGuidelineOrDict = Union[ApplicableGuideline, ApplicableGuidelineDict]


class ParsedResponse(_common.BaseModel):
    """Response for the optimize_prompt method."""

    optimization_type: Optional[str] = Field(default=None, description="""""")
    applicable_guidelines: Optional[list[ApplicableGuideline]] = Field(
        default=None, description=""""""
    )
    original_prompt: Optional[str] = Field(default=None, description="""""")
    suggested_prompt: Optional[str] = Field(default=None, description="""""")


class ParsedResponseDict(TypedDict, total=False):
    """Response for the optimize_prompt method."""

    optimization_type: Optional[str]
    """"""

    applicable_guidelines: Optional[list[ApplicableGuidelineDict]]
    """"""

    original_prompt: Optional[str]
    """"""

    suggested_prompt: Optional[str]
    """"""


ParsedResponseOrDict = Union[ParsedResponse, ParsedResponseDict]


class ParsedResponseFewShot(_common.BaseModel):
    """Response for the optimize_prompt method."""

    suggested_modifications: Optional[list[ApplicableGuideline]] = Field(
        default=None, description=""""""
    )
    original_system_instructions: Optional[str] = Field(
        default=None, description=""""""
    )
    new_system_instructions: Optional[str] = Field(default=None, description="""""")


class ParsedResponseFewShotDict(TypedDict, total=False):
    """Response for the optimize_prompt method."""

    suggested_modifications: Optional[list[ApplicableGuidelineDict]]
    """"""

    original_system_instructions: Optional[str]
    """"""

    new_system_instructions: Optional[str]
    """"""


ParsedResponseFewShotOrDict = Union[ParsedResponseFewShot, ParsedResponseFewShotDict]
