# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Code generated by the Google Gen AI SDK generator DO NOT EDIT.
# flake8: noqa: F401

import importlib
import typing

from . import agent_engines
from . import evals
from .common import _AppendAgentEngineSessionEventRequestParameters
from .common import _AssembleDatasetParameters
from .common import _AssessDatasetParameters
from .common import _CreateAgentEngineMemoryRequestParameters
from .common import _CreateAgentEngineRequestParameters
from .common import _CreateAgentEngineSandboxRequestParameters
from .common import _CreateAgentEngineSessionRequestParameters
from .common import _CreateDatasetParameters
from .common import _CreateDatasetVersionParameters
from .common import _CreateEvaluationItemParameters
from .common import _CreateEvaluationRunParameters
from .common import _CreateEvaluationSetParameters
from .common import _CreateMultimodalDatasetParameters
from .common import _CustomJobParameters
from .common import _DeleteAgentEngineMemoryRequestParameters
from .common import _DeleteAgentEngineRequestParameters
from .common import _DeleteAgentEngineSandboxRequestParameters
from .common import _DeleteAgentEngineSessionRequestParameters
from .common import _DeleteDatasetRequestParameters
from .common import _DeleteMultimodalDatasetRequestParameters
from .common import _DeletePromptVersionRequestParameters
from .common import _EvaluateInstancesRequestParameters
from .common import _ExecuteCodeAgentEngineSandboxRequestParameters
from .common import _GenerateAgentEngineMemoriesRequestParameters
from .common import _GenerateInstanceRubricsRequest
from .common import _GetAgentEngineGenerateMemoriesOperationParameters
from .common import _GetAgentEngineMemoryOperationParameters
from .common import _GetAgentEngineMemoryRequestParameters
from .common import _GetAgentEngineMemoryRevisionRequestParameters
from .common import _GetAgentEngineOperationParameters
from .common import _GetAgentEngineRequestParameters
from .common import _GetAgentEngineSandboxOperationParameters
from .common import _GetAgentEngineSandboxRequestParameters
from .common import _GetAgentEngineSessionOperationParameters
from .common import _GetAgentEngineSessionRequestParameters
from .common import _GetCustomJobParameters
from .common import _GetDatasetOperationParameters
from .common import _GetDatasetParameters
from .common import _GetDatasetVersionParameters
from .common import _GetEvaluationItemParameters
from .common import _GetEvaluationRunParameters
from .common import _GetEvaluationSetParameters
from .common import _GetMultimodalDatasetOperationParameters
from .common import _GetMultimodalDatasetParameters
from .common import _ListAgentEngineMemoryRequestParameters
from .common import _ListAgentEngineMemoryRevisionsRequestParameters
from .common import _ListAgentEngineRequestParameters
from .common import _ListAgentEngineSandboxesRequestParameters
from .common import _ListAgentEngineSessionEventsRequestParameters
from .common import _ListAgentEngineSessionsRequestParameters
from .common import _ListDatasetsRequestParameters
from .common import _ListDatasetVersionsRequestParameters
from .common import _ListMultimodalDatasetsRequestParameters
from .common import _OptimizeRequestParameters
from .common import _PurgeAgentEngineMemoriesRequestParameters
from .common import _QueryAgentEngineRequestParameters
from .common import _RestoreVersionRequestParameters
from .common import _RetrieveAgentEngineMemoriesRequestParameters
from .common import _RollbackAgentEngineMemoryRequestParameters
from .common import _UpdateAgentEngineMemoryRequestParameters
from .common import _UpdateAgentEngineRequestParameters
from .common import _UpdateAgentEngineSessionRequestParameters
from .common import _UpdateDatasetParameters
from .common import _UpdateMultimodalDatasetParameters
from .common import AcceleratorType
from .common import AgentEngine
from .common import AgentEngineConfig
from .common import AgentEngineConfigDict
from .common import AgentEngineConfigOrDict
from .common import AgentEngineDict
from .common import AgentEngineGenerateMemoriesOperation
from .common import AgentEngineGenerateMemoriesOperationDict
from .common import AgentEngineGenerateMemoriesOperationOrDict
from .common import AgentEngineMemoryConfig
from .common import AgentEngineMemoryConfigDict
from .common import AgentEngineMemoryConfigOrDict
from .common import AgentEngineMemoryOperation
from .common import AgentEngineMemoryOperationDict
from .common import AgentEngineMemoryOperationOrDict
from .common import AgentEngineOperation
from .common import AgentEngineOperationDict
from .common import AgentEngineOperationOrDict
from .common import AgentEngineOrDict
from .common import AgentEnginePurgeMemoriesOperation
from .common import AgentEnginePurgeMemoriesOperationDict
from .common import AgentEnginePurgeMemoriesOperationOrDict
from .common import AgentEngineRollbackMemoryOperation
from .common import AgentEngineRollbackMemoryOperationDict
from .common import AgentEngineRollbackMemoryOperationOrDict
from .common import AgentEngineSandboxOperation
from .common import AgentEngineSandboxOperationDict
from .common import AgentEngineSandboxOperationOrDict
from .common import AgentEngineSessionOperation
from .common import AgentEngineSessionOperationDict
from .common import AgentEngineSessionOperationOrDict
from .common import AgentServerMode
from .common import AggregatedMetricResult
from .common import AggregatedMetricResultDict
from .common import AggregatedMetricResultOrDict
from .common import AppendAgentEngineSessionEventConfig
from .common import AppendAgentEngineSessionEventConfigDict
from .common import AppendAgentEngineSessionEventConfigOrDict
from .common import AppendAgentEngineSessionEventResponse
from .common import AppendAgentEngineSessionEventResponseDict
from .common import AppendAgentEngineSessionEventResponseOrDict
from .common import ApplicableGuideline
from .common import ApplicableGuidelineDict
from .common import ApplicableGuidelineOrDict
from .common import AssembleDataset
from .common import AssembleDatasetConfig
from .common import AssembleDatasetConfigDict
from .common import AssembleDatasetConfigOrDict
from .common import AssembleDatasetDict
from .common import AssembleDatasetOrDict
from .common import AssessDatasetConfig
from .common import AssessDatasetConfigDict
from .common import AssessDatasetConfigOrDict
from .common import BatchPredictionResourceUsageAssessmentConfig
from .common import BatchPredictionResourceUsageAssessmentConfigDict
from .common import BatchPredictionResourceUsageAssessmentConfigOrDict
from .common import BatchPredictionResourceUsageAssessmentResult
from .common import BatchPredictionResourceUsageAssessmentResultDict
from .common import BatchPredictionResourceUsageAssessmentResultOrDict
from .common import BatchPredictionValidationAssessmentConfig
from .common import BatchPredictionValidationAssessmentConfigDict
from .common import BatchPredictionValidationAssessmentConfigOrDict
from .common import BigQueryRequestSet
from .common import BigQueryRequestSetDict
from .common import BigQueryRequestSetOrDict
from .common import BigQuerySource
from .common import BigQuerySourceDict
from .common import BigQuerySourceOrDict
from .common import BleuInput
from .common import BleuInputDict
from .common import BleuInputOrDict
from .common import BleuInstance
from .common import BleuInstanceDict
from .common import BleuInstanceOrDict
from .common import BleuMetricValue
from .common import BleuMetricValueDict
from .common import BleuMetricValueOrDict
from .common import BleuResults
from .common import BleuResultsDict
from .common import BleuResultsOrDict
from .common import CandidateResponse
from .common import CandidateResponseDict
from .common import CandidateResponseOrDict
from .common import CandidateResult
from .common import CandidateResultDict
from .common import Chunk
from .common import ChunkDict
from .common import ChunkOrDict
from .common import CometResult
from .common import CometResultDict
from .common import CometResultOrDict
from .common import ContainerSpec
from .common import ContainerSpecDict
from .common import ContainerSpecOrDict
from .common import ContentMap
from .common import ContentMapContents
from .common import ContentMapContentsDict
from .common import ContentMapContentsOrDict
from .common import ContentMapDict
from .common import ContentMapOrDict
from .common import CreateAgentEngineConfig
from .common import CreateAgentEngineConfigDict
from .common import CreateAgentEngineConfigOrDict
from .common import CreateAgentEngineSandboxConfig
from .common import CreateAgentEngineSandboxConfigDict
from .common import CreateAgentEngineSandboxConfigOrDict
from .common import CreateAgentEngineSessionConfig
from .common import CreateAgentEngineSessionConfigDict
from .common import CreateAgentEngineSessionConfigOrDict
from .common import CreateDatasetConfig
from .common import CreateDatasetConfigDict
from .common import CreateDatasetConfigOrDict
from .common import CreateDatasetVersionConfig
from .common import CreateDatasetVersionConfigDict
from .common import CreateDatasetVersionConfigOrDict
from .common import CreateEvaluationItemConfig
from .common import CreateEvaluationItemConfigDict
from .common import CreateEvaluationItemConfigOrDict
from .common import CreateEvaluationRunConfig
from .common import CreateEvaluationRunConfigDict
from .common import CreateEvaluationRunConfigOrDict
from .common import CreateEvaluationSetConfig
from .common import CreateEvaluationSetConfigDict
from .common import CreateEvaluationSetConfigOrDict
from .common import CreateMultimodalDatasetConfig
from .common import CreateMultimodalDatasetConfigDict
from .common import CreateMultimodalDatasetConfigOrDict
from .common import CreatePromptConfig
from .common import CreatePromptConfigDict
from .common import CreatePromptConfigOrDict
from .common import CreatePromptVersionConfig
from .common import CreatePromptVersionConfigDict
from .common import CreatePromptVersionConfigOrDict
from .common import CustomCodeExecutionSpec
from .common import CustomCodeExecutionSpecDict
from .common import CustomCodeExecutionSpecOrDict
from .common import CustomJob
from .common import CustomJobDict
from .common import CustomJobOrDict
from .common import CustomJobSpec
from .common import CustomJobSpecDict
from .common import CustomJobSpecOrDict
from .common import CustomOutput
from .common import CustomOutputDict
from .common import CustomOutputOrDict
from .common import Dataset
from .common import DatasetDict
from .common import DatasetOperation
from .common import DatasetOperationDict
from .common import DatasetOperationOrDict
from .common import DatasetOrDict
from .common import DatasetVersion
from .common import DatasetVersionDict
from .common import DatasetVersionOrDict
from .common import DeleteAgentEngineConfig
from .common import DeleteAgentEngineConfigDict
from .common import DeleteAgentEngineConfigOrDict
from .common import DeleteAgentEngineMemoryConfig
from .common import DeleteAgentEngineMemoryConfigDict
from .common import DeleteAgentEngineMemoryConfigOrDict
from .common import DeleteAgentEngineMemoryOperation
from .common import DeleteAgentEngineMemoryOperationDict
from .common import DeleteAgentEngineMemoryOperationOrDict
from .common import DeleteAgentEngineOperation
from .common import DeleteAgentEngineOperationDict
from .common import DeleteAgentEngineOperationOrDict
from .common import DeleteAgentEngineSandboxConfig
from .common import DeleteAgentEngineSandboxConfigDict
from .common import DeleteAgentEngineSandboxConfigOrDict
from .common import DeleteAgentEngineSandboxOperation
from .common import DeleteAgentEngineSandboxOperationDict
from .common import DeleteAgentEngineSandboxOperationOrDict
from .common import DeleteAgentEngineSessionConfig
from .common import DeleteAgentEngineSessionConfigDict
from .common import DeleteAgentEngineSessionConfigOrDict
from .common import DeleteAgentEngineSessionOperation
from .common import DeleteAgentEngineSessionOperationDict
from .common import DeleteAgentEngineSessionOperationOrDict
from .common import DeletePromptConfig
from .common import DeletePromptConfigDict
from .common import DeletePromptConfigOrDict
from .common import DeletePromptOperation
from .common import DeletePromptOperationDict
from .common import DeletePromptOperationOrDict
from .common import DeletePromptVersionOperation
from .common import DeletePromptVersionOperationDict
from .common import DeletePromptVersionOperationOrDict
from .common import DiskSpec
from .common import DiskSpecDict
from .common import DiskSpecOrDict
from .common import DnsPeeringConfig
from .common import DnsPeeringConfigDict
from .common import DnsPeeringConfigOrDict
from .common import EnvVar
from .common import EnvVarDict
from .common import EnvVarOrDict
from .common import EvalCase
from .common import EvalCaseDict
from .common import EvalCaseMetricResult
from .common import EvalCaseMetricResultDict
from .common import EvalCaseMetricResultOrDict
from .common import EvalCaseOrDict
from .common import EvalCaseResult
from .common import EvalCaseResultDict
from .common import EvalCaseResultOrDict
from .common import EvalRunInferenceConfig
from .common import EvalRunInferenceConfigDict
from .common import EvalRunInferenceConfigOrDict
from .common import EvaluateDatasetConfig
from .common import EvaluateDatasetConfigDict
from .common import EvaluateDatasetConfigOrDict
from .common import EvaluateDatasetOperation
from .common import EvaluateDatasetOperationDict
from .common import EvaluateDatasetOperationOrDict
from .common import EvaluateDatasetRequestParameters
from .common import EvaluateDatasetRequestParametersDict
from .common import EvaluateDatasetRequestParametersOrDict
from .common import EvaluateInstancesConfig
from .common import EvaluateInstancesConfigDict
from .common import EvaluateInstancesConfigOrDict
from .common import EvaluateInstancesResponse
from .common import EvaluateInstancesResponseDict
from .common import EvaluateInstancesResponseOrDict
from .common import EvaluateMethodConfig
from .common import EvaluateMethodConfigDict
from .common import EvaluateMethodConfigOrDict
from .common import EvaluationDataset
from .common import EvaluationDatasetDict
from .common import EvaluationDatasetOrDict
from .common import EvaluationInstance
from .common import EvaluationInstanceDict
from .common import EvaluationInstanceOrDict
from .common import EvaluationItem
from .common import EvaluationItemDict
from .common import EvaluationItemOrDict
from .common import EvaluationItemRequest
from .common import EvaluationItemRequestDict
from .common import EvaluationItemRequestOrDict
from .common import EvaluationItemResult
from .common import EvaluationItemResultDict
from .common import EvaluationItemResultOrDict
from .common import EvaluationItemType
from .common import EvaluationPrompt
from .common import EvaluationPromptDict
from .common import EvaluationPromptOrDict
from .common import EvaluationResult
from .common import EvaluationResultDict
from .common import EvaluationResultOrDict
from .common import EvaluationRun
from .common import EvaluationRunAgentConfig
from .common import EvaluationRunAgentConfigDict
from .common import EvaluationRunAgentConfigOrDict
from .common import EvaluationRunConfig
from .common import EvaluationRunConfigDict
from .common import EvaluationRunConfigOrDict
from .common import EvaluationRunDataSource
from .common import EvaluationRunDataSourceDict
from .common import EvaluationRunDataSourceOrDict
from .common import EvaluationRunDict
from .common import EvaluationRunInferenceConfig
from .common import EvaluationRunInferenceConfigDict
from .common import EvaluationRunInferenceConfigOrDict
from .common import EvaluationRunMetadata
from .common import EvaluationRunMetadataDict
from .common import EvaluationRunMetadataOrDict
from .common import EvaluationRunMetric
from .common import EvaluationRunMetricDict
from .common import EvaluationRunMetricOrDict
from .common import EvaluationRunOrDict
from .common import EvaluationRunResults
from .common import EvaluationRunResultsDict
from .common import EvaluationRunResultsOrDict
from .common import EvaluationRunState
from .common import EvaluationSet
from .common import EvaluationSetDict
from .common import EvaluationSetOrDict
from .common import Event
from .common import EventActions
from .common import EventActionsDict
from .common import EventActionsOrDict
from .common import EventDict
from .common import EventMetadata
from .common import EventMetadataDict
from .common import EventMetadataOrDict
from .common import ExactMatchInput
from .common import ExactMatchInputDict
from .common import ExactMatchInputOrDict
from .common import ExactMatchInstance
from .common import ExactMatchInstanceDict
from .common import ExactMatchInstanceOrDict
from .common import ExactMatchMetricValue
from .common import ExactMatchMetricValueDict
from .common import ExactMatchMetricValueOrDict
from .common import ExactMatchResults
from .common import ExactMatchResultsDict
from .common import ExactMatchResultsOrDict
from .common import ExactMatchSpec
from .common import ExactMatchSpecDict
from .common import ExactMatchSpecOrDict
from .common import ExecuteCodeAgentEngineSandboxConfig
from .common import ExecuteCodeAgentEngineSandboxConfigDict
from .common import ExecuteCodeAgentEngineSandboxConfigOrDict
from .common import ExecuteSandboxEnvironmentResponse
from .common import ExecuteSandboxEnvironmentResponseDict
from .common import ExecuteSandboxEnvironmentResponseOrDict
from .common import GcsSource
from .common import GcsSourceDict
from .common import GcsSourceOrDict
from .common import GeminiExample
from .common import GeminiExampleDict
from .common import GeminiExampleOrDict
from .common import GeminiRequestReadConfig
from .common import GeminiRequestReadConfigDict
from .common import GeminiRequestReadConfigOrDict
from .common import GeminiTemplateConfig
from .common import GeminiTemplateConfigDict
from .common import GeminiTemplateConfigOrDict
from .common import GenerateAgentEngineMemoriesConfig
from .common import GenerateAgentEngineMemoriesConfigDict
from .common import GenerateAgentEngineMemoriesConfigOrDict
from .common import GenerateInstanceRubricsResponse
from .common import GenerateInstanceRubricsResponseDict
from .common import GenerateInstanceRubricsResponseOrDict
from .common import GenerateMemoriesRequestDirectContentsSource
from .common import GenerateMemoriesRequestDirectContentsSourceDict
from .common import GenerateMemoriesRequestDirectContentsSourceEvent
from .common import GenerateMemoriesRequestDirectContentsSourceEventDict
from .common import GenerateMemoriesRequestDirectContentsSourceEventOrDict
from .common import GenerateMemoriesRequestDirectContentsSourceOrDict
from .common import GenerateMemoriesRequestDirectMemoriesSource
from .common import GenerateMemoriesRequestDirectMemoriesSourceDict
from .common import GenerateMemoriesRequestDirectMemoriesSourceDirectMemory
from .common import GenerateMemoriesRequestDirectMemoriesSourceDirectMemoryDict
from .common import GenerateMemoriesRequestDirectMemoriesSourceDirectMemoryOrDict
from .common import GenerateMemoriesRequestDirectMemoriesSourceOrDict
from .common import GenerateMemoriesRequestVertexSessionSource
from .common import GenerateMemoriesRequestVertexSessionSourceDict
from .common import GenerateMemoriesRequestVertexSessionSourceOrDict
from .common import GenerateMemoriesResponse
from .common import GenerateMemoriesResponseDict
from .common import GenerateMemoriesResponseGeneratedMemory
from .common import GenerateMemoriesResponseGeneratedMemoryAction
from .common import GenerateMemoriesResponseGeneratedMemoryDict
from .common import GenerateMemoriesResponseGeneratedMemoryOrDict
from .common import GenerateMemoriesResponseOrDict
from .common import GetAgentEngineConfig
from .common import GetAgentEngineConfigDict
from .common import GetAgentEngineConfigOrDict
from .common import GetAgentEngineMemoryConfig
from .common import GetAgentEngineMemoryConfigDict
from .common import GetAgentEngineMemoryConfigOrDict
from .common import GetAgentEngineMemoryRevisionConfig
from .common import GetAgentEngineMemoryRevisionConfigDict
from .common import GetAgentEngineMemoryRevisionConfigOrDict
from .common import GetAgentEngineOperationConfig
from .common import GetAgentEngineOperationConfigDict
from .common import GetAgentEngineOperationConfigOrDict
from .common import GetAgentEngineSandboxConfig
from .common import GetAgentEngineSandboxConfigDict
from .common import GetAgentEngineSandboxConfigOrDict
from .common import GetAgentEngineSessionConfig
from .common import GetAgentEngineSessionConfigDict
from .common import GetAgentEngineSessionConfigOrDict
from .common import GetDatasetOperationConfig
from .common import GetDatasetOperationConfigDict
from .common import GetDatasetOperationConfigOrDict
from .common import GetEvaluationItemConfig
from .common import GetEvaluationItemConfigDict
from .common import GetEvaluationItemConfigOrDict
from .common import GetEvaluationRunConfig
from .common import GetEvaluationRunConfigDict
from .common import GetEvaluationRunConfigOrDict
from .common import GetEvaluationSetConfig
from .common import GetEvaluationSetConfigDict
from .common import GetEvaluationSetConfigOrDict
from .common import GetMultimodalDatasetOperationConfig
from .common import GetMultimodalDatasetOperationConfigDict
from .common import GetMultimodalDatasetOperationConfigOrDict
from .common import GetPromptConfig
from .common import GetPromptConfigDict
from .common import GetPromptConfigOrDict
from .common import IdentityType
from .common import Importance
from .common import IntermediateExtractedMemory
from .common import IntermediateExtractedMemoryDict
from .common import IntermediateExtractedMemoryOrDict
from .common import JobState
from .common import Language
from .common import ListAgentEngineConfig
from .common import ListAgentEngineConfigDict
from .common import ListAgentEngineConfigOrDict
from .common import ListAgentEngineMemoryConfig
from .common import ListAgentEngineMemoryConfigDict
from .common import ListAgentEngineMemoryConfigOrDict
from .common import ListAgentEngineMemoryRevisionsConfig
from .common import ListAgentEngineMemoryRevisionsConfigDict
from .common import ListAgentEngineMemoryRevisionsConfigOrDict
from .common import ListAgentEngineMemoryRevisionsResponse
from .common import ListAgentEngineMemoryRevisionsResponseDict
from .common import ListAgentEngineMemoryRevisionsResponseOrDict
from .common import ListAgentEngineSandboxesConfig
from .common import ListAgentEngineSandboxesConfigDict
from .common import ListAgentEngineSandboxesConfigOrDict
from .common import ListAgentEngineSandboxesResponse
from .common import ListAgentEngineSandboxesResponseDict
from .common import ListAgentEngineSandboxesResponseOrDict
from .common import ListAgentEngineSessionEventsConfig
from .common import ListAgentEngineSessionEventsConfigDict
from .common import ListAgentEngineSessionEventsConfigOrDict
from .common import ListAgentEngineSessionEventsResponse
from .common import ListAgentEngineSessionEventsResponseDict
from .common import ListAgentEngineSessionEventsResponseOrDict
from .common import ListAgentEngineSessionsConfig
from .common import ListAgentEngineSessionsConfigDict
from .common import ListAgentEngineSessionsConfigOrDict
from .common import ListDatasetsResponse
from .common import ListDatasetsResponseDict
from .common import ListDatasetsResponseOrDict
from .common import ListDatasetVersionsResponse
from .common import ListDatasetVersionsResponseDict
from .common import ListDatasetVersionsResponseOrDict
from .common import ListMultimodalDatasetsConfig
from .common import ListMultimodalDatasetsConfigDict
from .common import ListMultimodalDatasetsConfigOrDict
from .common import ListMultimodalDatasetsResponse
from .common import ListMultimodalDatasetsResponseDict
from .common import ListMultimodalDatasetsResponseOrDict
from .common import ListPromptsConfig
from .common import ListPromptsConfigDict
from .common import ListPromptsConfigOrDict
from .common import ListReasoningEnginesMemoriesResponse
from .common import ListReasoningEnginesMemoriesResponseDict
from .common import ListReasoningEnginesMemoriesResponseOrDict
from .common import ListReasoningEnginesResponse
from .common import ListReasoningEnginesResponseDict
from .common import ListReasoningEnginesResponseOrDict
from .common import ListReasoningEnginesSessionsResponse
from .common import ListReasoningEnginesSessionsResponseDict
from .common import ListReasoningEnginesSessionsResponseOrDict
from .common import LLMBasedMetricSpec
from .common import LLMBasedMetricSpecDict
from .common import LLMBasedMetricSpecOrDict
from .common import LLMMetric
from .common import LustreMount
from .common import LustreMountDict
from .common import LustreMountOrDict
from .common import MachineConfig
from .common import MachineSpec
from .common import MachineSpecDict
from .common import MachineSpecOrDict
from .common import ManagedTopicEnum
from .common import MapInstance
from .common import MapInstanceDict
from .common import MapInstanceOrDict
from .common import Memory
from .common import MemoryBankCustomizationConfig
from .common import MemoryBankCustomizationConfigDict
from .common import MemoryBankCustomizationConfigGenerateMemoriesExample
from .common import (
    MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSource,
)
from .common import (
    MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSourceDict,
)
from .common import (
    MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSourceEvent,
)
from .common import (
    MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSourceEventDict,
)
from .common import (
    MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSourceEventOrDict,
)
from .common import (
    MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSourceOrDict,
)
from .common import MemoryBankCustomizationConfigGenerateMemoriesExampleDict
from .common import MemoryBankCustomizationConfigGenerateMemoriesExampleGeneratedMemory
from .common import (
    MemoryBankCustomizationConfigGenerateMemoriesExampleGeneratedMemoryDict,
)
from .common import (
    MemoryBankCustomizationConfigGenerateMemoriesExampleGeneratedMemoryOrDict,
)
from .common import MemoryBankCustomizationConfigGenerateMemoriesExampleOrDict
from .common import MemoryBankCustomizationConfigMemoryTopic
from .common import MemoryBankCustomizationConfigMemoryTopicCustomMemoryTopic
from .common import MemoryBankCustomizationConfigMemoryTopicCustomMemoryTopicDict
from .common import MemoryBankCustomizationConfigMemoryTopicCustomMemoryTopicOrDict
from .common import MemoryBankCustomizationConfigMemoryTopicDict
from .common import MemoryBankCustomizationConfigMemoryTopicManagedMemoryTopic
from .common import MemoryBankCustomizationConfigMemoryTopicManagedMemoryTopicDict
from .common import MemoryBankCustomizationConfigMemoryTopicManagedMemoryTopicOrDict
from .common import MemoryBankCustomizationConfigMemoryTopicOrDict
from .common import MemoryBankCustomizationConfigOrDict
from .common import MemoryDict
from .common import MemoryOrDict
from .common import MemoryRevision
from .common import MemoryRevisionDict
from .common import MemoryRevisionOrDict
from .common import MemoryTopicId
from .common import MemoryTopicIdDict
from .common import MemoryTopicIdOrDict
from .common import Message
from .common import MessageDict
from .common import Metadata
from .common import MetadataDict
from .common import MetadataOrDict
from .common import Metric
from .common import MetricDict
from .common import MetricOrDict
from .common import MetricPromptBuilder
from .common import MetricResult
from .common import MetricResultDict
from .common import MetricResultOrDict
from .common import MetricxResult
from .common import MetricxResultDict
from .common import MetricxResultOrDict
from .common import MultimodalDataset
from .common import MultimodalDatasetDict
from .common import MultimodalDatasetOperation
from .common import MultimodalDatasetOperationDict
from .common import MultimodalDatasetOperationOrDict
from .common import MultimodalDatasetOrDict
from .common import NfsMount
from .common import NfsMountDict
from .common import NfsMountOrDict
from .common import ObservabilityEvalCase
from .common import ObservabilityEvalCaseDict
from .common import ObservabilityEvalCaseOrDict
from .common import OptimizeConfig
from .common import OptimizeConfigDict
from .common import OptimizeConfigOrDict
from .common import OptimizeResponse
from .common import OptimizeResponseDict
from .common import OptimizeResponseEndpoint
from .common import OptimizeResponseEndpointDict
from .common import OptimizeResponseEndpointOrDict
from .common import OptimizeResponseOrDict
from .common import OptimizeTarget
from .common import PairwiseChoice
from .common import PairwiseMetricInput
from .common import PairwiseMetricInputDict
from .common import PairwiseMetricInputOrDict
from .common import PairwiseMetricInstance
from .common import PairwiseMetricInstanceDict
from .common import PairwiseMetricInstanceOrDict
from .common import PairwiseMetricResult
from .common import PairwiseMetricResultDict
from .common import PairwiseMetricResultOrDict
from .common import ParsedResponse
from .common import ParsedResponseDict
from .common import ParsedResponseOrDict
from .common import PointwiseMetricInput
from .common import PointwiseMetricInputDict
from .common import PointwiseMetricInputOrDict
from .common import PointwiseMetricInstance
from .common import PointwiseMetricInstanceDict
from .common import PointwiseMetricInstanceOrDict
from .common import PointwiseMetricResult
from .common import PointwiseMetricResultDict
from .common import PointwiseMetricResultOrDict
from .common import PredefinedMetricSpec
from .common import PredefinedMetricSpecDict
from .common import PredefinedMetricSpecOrDict
from .common import Prompt
from .common import PromptData
from .common import PromptDataDict
from .common import PromptDataOrDict
from .common import PromptDict
from .common import PromptOptimizerConfig
from .common import PromptOptimizerConfigDict
from .common import PromptOptimizerConfigOrDict
from .common import PromptOptimizerMethod
from .common import PromptOrDict
from .common import PromptRef
from .common import PromptRefDict
from .common import PromptRefOrDict
from .common import PromptTemplate
from .common import PromptTemplateData
from .common import PromptTemplateDataDict
from .common import PromptTemplateDataOrDict
from .common import PromptTemplateDict
from .common import PromptTemplateOrDict
from .common import PromptVersionRef
from .common import PromptVersionRefDict
from .common import PromptVersionRefOrDict
from .common import PscInterfaceConfig
from .common import PscInterfaceConfigDict
from .common import PscInterfaceConfigOrDict
from .common import PurgeAgentEngineMemoriesConfig
from .common import PurgeAgentEngineMemoriesConfigDict
from .common import PurgeAgentEngineMemoriesConfigOrDict
from .common import PurgeMemoriesResponse
from .common import PurgeMemoriesResponseDict
from .common import PurgeMemoriesResponseOrDict
from .common import PythonPackageSpec
from .common import PythonPackageSpecDict
from .common import PythonPackageSpecOrDict
from .common import QueryAgentEngineConfig
from .common import QueryAgentEngineConfigDict
from .common import QueryAgentEngineConfigOrDict
from .common import QueryReasoningEngineResponse
from .common import QueryReasoningEngineResponseDict
from .common import QueryReasoningEngineResponseOrDict
from .common import RawOutput
from .common import RawOutputDict
from .common import RawOutputOrDict
from .common import ReasoningEngine
from .common import ReasoningEngineContextSpec
from .common import ReasoningEngineContextSpecDict
from .common import ReasoningEngineContextSpecMemoryBankConfig
from .common import ReasoningEngineContextSpecMemoryBankConfigDict
from .common import ReasoningEngineContextSpecMemoryBankConfigGenerationConfig
from .common import ReasoningEngineContextSpecMemoryBankConfigGenerationConfigDict
from .common import ReasoningEngineContextSpecMemoryBankConfigGenerationConfigOrDict
from .common import ReasoningEngineContextSpecMemoryBankConfigOrDict
from .common import ReasoningEngineContextSpecMemoryBankConfigSimilaritySearchConfig
from .common import ReasoningEngineContextSpecMemoryBankConfigSimilaritySearchConfigDict
from .common import (
    ReasoningEngineContextSpecMemoryBankConfigSimilaritySearchConfigOrDict,
)
from .common import ReasoningEngineContextSpecMemoryBankConfigTtlConfig
from .common import ReasoningEngineContextSpecMemoryBankConfigTtlConfigDict
from .common import ReasoningEngineContextSpecMemoryBankConfigTtlConfigGranularTtlConfig
from .common import (
    ReasoningEngineContextSpecMemoryBankConfigTtlConfigGranularTtlConfigDict,
)
from .common import (
    ReasoningEngineContextSpecMemoryBankConfigTtlConfigGranularTtlConfigOrDict,
)
from .common import ReasoningEngineContextSpecMemoryBankConfigTtlConfigOrDict
from .common import ReasoningEngineContextSpecOrDict
from .common import ReasoningEngineDict
from .common import ReasoningEngineOrDict
from .common import ReasoningEngineSpec
from .common import ReasoningEngineSpecDeploymentSpec
from .common import ReasoningEngineSpecDeploymentSpecDict
from .common import ReasoningEngineSpecDeploymentSpecOrDict
from .common import ReasoningEngineSpecDict
from .common import ReasoningEngineSpecOrDict
from .common import ReasoningEngineSpecPackageSpec
from .common import ReasoningEngineSpecPackageSpecDict
from .common import ReasoningEngineSpecPackageSpecOrDict
from .common import ReasoningEngineSpecSourceCodeSpec
from .common import ReasoningEngineSpecSourceCodeSpecDict
from .common import ReasoningEngineSpecSourceCodeSpecInlineSource
from .common import ReasoningEngineSpecSourceCodeSpecInlineSourceDict
from .common import ReasoningEngineSpecSourceCodeSpecInlineSourceOrDict
from .common import ReasoningEngineSpecSourceCodeSpecOrDict
from .common import ReasoningEngineSpecSourceCodeSpecPythonSpec
from .common import ReasoningEngineSpecSourceCodeSpecPythonSpecDict
from .common import ReasoningEngineSpecSourceCodeSpecPythonSpecOrDict
from .common import ReservationAffinity
from .common import ReservationAffinityDict
from .common import ReservationAffinityOrDict
from .common import ResponseCandidate
from .common import ResponseCandidateDict
from .common import ResponseCandidateOrDict
from .common import ResponseCandidateResult
from .common import ResponseCandidateResultDict
from .common import ResponseCandidateResultOrDict
from .common import RestoreVersionConfig
from .common import RestoreVersionConfigDict
from .common import RestoreVersionConfigOrDict
from .common import RestoreVersionOperation
from .common import RestoreVersionOperationDict
from .common import RestoreVersionOperationOrDict
from .common import RetrieveAgentEngineMemoriesConfig
from .common import RetrieveAgentEngineMemoriesConfigDict
from .common import RetrieveAgentEngineMemoriesConfigOrDict
from .common import RetrieveMemoriesRequestSimilaritySearchParams
from .common import RetrieveMemoriesRequestSimilaritySearchParamsDict
from .common import RetrieveMemoriesRequestSimilaritySearchParamsOrDict
from .common import RetrieveMemoriesRequestSimpleRetrievalParams
from .common import RetrieveMemoriesRequestSimpleRetrievalParamsDict
from .common import RetrieveMemoriesRequestSimpleRetrievalParamsOrDict
from .common import RetrieveMemoriesResponse
from .common import RetrieveMemoriesResponseDict
from .common import RetrieveMemoriesResponseOrDict
from .common import RetrieveMemoriesResponseRetrievedMemory
from .common import RetrieveMemoriesResponseRetrievedMemoryDict
from .common import RetrieveMemoriesResponseRetrievedMemoryOrDict
from .common import RollbackAgentEngineMemoryConfig
from .common import RollbackAgentEngineMemoryConfigDict
from .common import RollbackAgentEngineMemoryConfigOrDict
from .common import RougeInput
from .common import RougeInputDict
from .common import RougeInputOrDict
from .common import RougeInstance
from .common import RougeInstanceDict
from .common import RougeInstanceOrDict
from .common import RougeMetricValue
from .common import RougeMetricValueDict
from .common import RougeMetricValueOrDict
from .common import RougeResults
from .common import RougeResultsDict
from .common import RougeResultsOrDict
from .common import Rubric
from .common import RubricBasedMetricInput
from .common import RubricBasedMetricInputDict
from .common import RubricBasedMetricInputOrDict
from .common import RubricBasedMetricInstance
from .common import RubricBasedMetricInstanceDict
from .common import RubricBasedMetricInstanceOrDict
from .common import RubricBasedMetricResult
from .common import RubricBasedMetricResultDict
from .common import RubricBasedMetricResultOrDict
from .common import RubricBasedMetricSpec
from .common import RubricBasedMetricSpecDict
from .common import RubricBasedMetricSpecOrDict
from .common import RubricContent
from .common import RubricContentDict
from .common import RubricContentProperty
from .common import RubricContentPropertyDict
from .common import RubricContentType
from .common import RubricDict
from .common import RubricEnhancedContents
from .common import RubricEnhancedContentsDict
from .common import RubricEnhancedContentsOrDict
from .common import RubricGenerationConfig
from .common import RubricGenerationConfigDict
from .common import RubricGenerationConfigOrDict
from .common import RubricGenerationSpec
from .common import RubricGenerationSpecDict
from .common import RubricGenerationSpecOrDict
from .common import RubricGroup
from .common import RubricGroupDict
from .common import RubricGroupOrDict
from .common import RubricVerdict
from .common import RubricVerdictDict
from .common import SamplingConfig
from .common import SamplingConfigDict
from .common import SamplingConfigOrDict
from .common import SamplingMethod
from .common import SandboxEnvironment
from .common import SandboxEnvironmentConnectionInfo
from .common import SandboxEnvironmentConnectionInfoDict
from .common import SandboxEnvironmentConnectionInfoOrDict
from .common import SandboxEnvironmentDict
from .common import SandboxEnvironmentOrDict
from .common import SandboxEnvironmentSpec
from .common import SandboxEnvironmentSpecCodeExecutionEnvironment
from .common import SandboxEnvironmentSpecCodeExecutionEnvironmentDict
from .common import SandboxEnvironmentSpecCodeExecutionEnvironmentOrDict
from .common import SandboxEnvironmentSpecComputerUseEnvironment
from .common import SandboxEnvironmentSpecComputerUseEnvironmentDict
from .common import SandboxEnvironmentSpecComputerUseEnvironmentOrDict
from .common import SandboxEnvironmentSpecDict
from .common import SandboxEnvironmentSpecOrDict
from .common import SavedQuery
from .common import SavedQueryDict
from .common import SavedQueryOrDict
from .common import Scheduling
from .common import SchedulingDict
from .common import SchedulingOrDict
from .common import SchemaPredictParamsGroundingConfig
from .common import SchemaPredictParamsGroundingConfigDict
from .common import SchemaPredictParamsGroundingConfigOrDict
from .common import SchemaPredictParamsGroundingConfigSourceEntry
from .common import SchemaPredictParamsGroundingConfigSourceEntryDict
from .common import SchemaPredictParamsGroundingConfigSourceEntryOrDict
from .common import SchemaPromptApiSchema
from .common import SchemaPromptApiSchemaDict
from .common import SchemaPromptApiSchemaOrDict
from .common import SchemaPromptInstancePromptExecution
from .common import SchemaPromptInstancePromptExecutionDict
from .common import SchemaPromptInstancePromptExecutionOrDict
from .common import SchemaPromptInstanceVariableValue
from .common import SchemaPromptInstanceVariableValueDict
from .common import SchemaPromptInstanceVariableValueOrDict
from .common import SchemaPromptSpecMultimodalPrompt
from .common import SchemaPromptSpecMultimodalPromptDict
from .common import SchemaPromptSpecMultimodalPromptOrDict
from .common import SchemaPromptSpecPartList
from .common import SchemaPromptSpecPartListDict
from .common import SchemaPromptSpecPartListOrDict
from .common import SchemaPromptSpecPromptMessage
from .common import SchemaPromptSpecPromptMessageDict
from .common import SchemaPromptSpecPromptMessageOrDict
from .common import SchemaPromptSpecReferenceSentencePair
from .common import SchemaPromptSpecReferenceSentencePairDict
from .common import SchemaPromptSpecReferenceSentencePairList
from .common import SchemaPromptSpecReferenceSentencePairListDict
from .common import SchemaPromptSpecReferenceSentencePairListOrDict
from .common import SchemaPromptSpecReferenceSentencePairOrDict
from .common import SchemaPromptSpecStructuredPrompt
from .common import SchemaPromptSpecStructuredPromptDict
from .common import SchemaPromptSpecStructuredPromptOrDict
from .common import SchemaPromptSpecTranslationExample
from .common import SchemaPromptSpecTranslationExampleDict
from .common import SchemaPromptSpecTranslationExampleOrDict
from .common import SchemaPromptSpecTranslationFileInputSource
from .common import SchemaPromptSpecTranslationFileInputSourceDict
from .common import SchemaPromptSpecTranslationFileInputSourceOrDict
from .common import SchemaPromptSpecTranslationGcsInputSource
from .common import SchemaPromptSpecTranslationGcsInputSourceDict
from .common import SchemaPromptSpecTranslationGcsInputSourceOrDict
from .common import SchemaPromptSpecTranslationOption
from .common import SchemaPromptSpecTranslationOptionDict
from .common import SchemaPromptSpecTranslationOptionOrDict
from .common import SchemaPromptSpecTranslationPrompt
from .common import SchemaPromptSpecTranslationPromptDict
from .common import SchemaPromptSpecTranslationPromptOrDict
from .common import SchemaPromptSpecTranslationSentenceFileInput
from .common import SchemaPromptSpecTranslationSentenceFileInputDict
from .common import SchemaPromptSpecTranslationSentenceFileInputOrDict
from .common import SchemaTablesDatasetMetadata
from .common import SchemaTablesDatasetMetadataBigQuerySource
from .common import SchemaTablesDatasetMetadataBigQuerySourceDict
from .common import SchemaTablesDatasetMetadataBigQuerySourceOrDict
from .common import SchemaTablesDatasetMetadataDict
from .common import SchemaTablesDatasetMetadataInputConfig
from .common import SchemaTablesDatasetMetadataInputConfigDict
from .common import SchemaTablesDatasetMetadataInputConfigOrDict
from .common import SchemaTablesDatasetMetadataOrDict
from .common import SchemaTextPromptDatasetMetadata
from .common import SchemaTextPromptDatasetMetadataDict
from .common import SchemaTextPromptDatasetMetadataOrDict
from .common import SecretEnvVar
from .common import SecretEnvVarDict
from .common import SecretEnvVarOrDict
from .common import SecretRef
from .common import SecretRefDict
from .common import SecretRefOrDict
from .common import Session
from .common import SessionDict
from .common import SessionEvent
from .common import SessionEventDict
from .common import SessionEventOrDict
from .common import SessionOrDict
from .common import State
from .common import Strategy
from .common import SummaryMetric
from .common import SummaryMetricDict
from .common import SummaryMetricOrDict
from .common import ToolCallValidInput
from .common import ToolCallValidInputDict
from .common import ToolCallValidInputOrDict
from .common import ToolCallValidInstance
from .common import ToolCallValidInstanceDict
from .common import ToolCallValidInstanceOrDict
from .common import ToolCallValidMetricValue
from .common import ToolCallValidMetricValueDict
from .common import ToolCallValidMetricValueOrDict
from .common import ToolCallValidResults
from .common import ToolCallValidResultsDict
from .common import ToolCallValidResultsOrDict
from .common import ToolCallValidSpec
from .common import ToolCallValidSpecDict
from .common import ToolCallValidSpecOrDict
from .common import ToolNameMatchInput
from .common import ToolNameMatchInputDict
from .common import ToolNameMatchInputOrDict
from .common import ToolNameMatchInstance
from .common import ToolNameMatchInstanceDict
from .common import ToolNameMatchInstanceOrDict
from .common import ToolNameMatchMetricValue
from .common import ToolNameMatchMetricValueDict
from .common import ToolNameMatchMetricValueOrDict
from .common import ToolNameMatchResults
from .common import ToolNameMatchResultsDict
from .common import ToolNameMatchResultsOrDict
from .common import ToolNameMatchSpec
from .common import ToolNameMatchSpecDict
from .common import ToolNameMatchSpecOrDict
from .common import ToolParameterKeyMatchInput
from .common import ToolParameterKeyMatchInputDict
from .common import ToolParameterKeyMatchInputOrDict
from .common import ToolParameterKeyMatchInstance
from .common import ToolParameterKeyMatchInstanceDict
from .common import ToolParameterKeyMatchInstanceOrDict
from .common import ToolParameterKeyMatchMetricValue
from .common import ToolParameterKeyMatchMetricValueDict
from .common import ToolParameterKeyMatchMetricValueOrDict
from .common import ToolParameterKeyMatchResults
from .common import ToolParameterKeyMatchResultsDict
from .common import ToolParameterKeyMatchResultsOrDict
from .common import ToolParameterKeyMatchSpec
from .common import ToolParameterKeyMatchSpecDict
from .common import ToolParameterKeyMatchSpecOrDict
from .common import ToolParameterKVMatchInput
from .common import ToolParameterKVMatchInputDict
from .common import ToolParameterKVMatchInputOrDict
from .common import ToolParameterKVMatchInstance
from .common import ToolParameterKVMatchInstanceDict
from .common import ToolParameterKVMatchInstanceOrDict
from .common import ToolParameterKVMatchMetricValue
from .common import ToolParameterKVMatchMetricValueDict
from .common import ToolParameterKVMatchMetricValueOrDict
from .common import ToolParameterKVMatchResults
from .common import ToolParameterKVMatchResultsDict
from .common import ToolParameterKVMatchResultsOrDict
from .common import ToolParameterKVMatchSpec
from .common import ToolParameterKVMatchSpecDict
from .common import ToolParameterKVMatchSpecOrDict
from .common import TuningResourceUsageAssessmentConfig
from .common import TuningResourceUsageAssessmentConfigDict
from .common import TuningResourceUsageAssessmentConfigOrDict
from .common import TuningResourceUsageAssessmentResult
from .common import TuningResourceUsageAssessmentResultDict
from .common import TuningResourceUsageAssessmentResultOrDict
from .common import TuningValidationAssessmentConfig
from .common import TuningValidationAssessmentConfigDict
from .common import TuningValidationAssessmentConfigOrDict
from .common import TuningValidationAssessmentResult
from .common import TuningValidationAssessmentResultDict
from .common import TuningValidationAssessmentResultOrDict
from .common import Type
from .common import UnifiedMetric
from .common import UnifiedMetricDict
from .common import UnifiedMetricOrDict
from .common import UpdateAgentEngineConfig
from .common import UpdateAgentEngineConfigDict
from .common import UpdateAgentEngineConfigOrDict
from .common import UpdateAgentEngineMemoryConfig
from .common import UpdateAgentEngineMemoryConfigDict
from .common import UpdateAgentEngineMemoryConfigOrDict
from .common import UpdateAgentEngineSessionConfig
from .common import UpdateAgentEngineSessionConfigDict
from .common import UpdateAgentEngineSessionConfigOrDict
from .common import UpdateDatasetConfig
from .common import UpdateDatasetConfigDict
from .common import UpdateDatasetConfigOrDict
from .common import UpdateMultimodalDatasetConfig
from .common import UpdateMultimodalDatasetConfigDict
from .common import UpdateMultimodalDatasetConfigOrDict
from .common import VertexBaseConfig
from .common import VertexBaseConfigDict
from .common import VertexBaseConfigOrDict
from .common import WinRateStats
from .common import WinRateStatsDict
from .common import WinRateStatsOrDict
from .common import WorkerPoolSpec
from .common import WorkerPoolSpecDict
from .common import WorkerPoolSpecOrDict

__all__ = [
    "CreateEvaluationItemConfig",
    "CreateEvaluationItemConfigDict",
    "CreateEvaluationItemConfigOrDict",
    "PromptTemplateData",
    "PromptTemplateDataDict",
    "PromptTemplateDataOrDict",
    "EvaluationPrompt",
    "EvaluationPromptDict",
    "EvaluationPromptOrDict",
    "CandidateResponse",
    "CandidateResponseDict",
    "CandidateResponseOrDict",
    "EvaluationItemRequest",
    "EvaluationItemRequestDict",
    "EvaluationItemRequestOrDict",
    "EvaluationItemResult",
    "EvaluationItemResultDict",
    "EvaluationItemResultOrDict",
    "EvaluationItem",
    "EvaluationItemDict",
    "EvaluationItemOrDict",
    "SamplingConfig",
    "SamplingConfigDict",
    "SamplingConfigOrDict",
    "BigQueryRequestSet",
    "BigQueryRequestSetDict",
    "BigQueryRequestSetOrDict",
    "EvaluationRunDataSource",
    "EvaluationRunDataSourceDict",
    "EvaluationRunDataSourceOrDict",
    "PredefinedMetricSpec",
    "PredefinedMetricSpecDict",
    "PredefinedMetricSpecOrDict",
    "RubricGenerationSpec",
    "RubricGenerationSpecDict",
    "RubricGenerationSpecOrDict",
    "LLMBasedMetricSpec",
    "LLMBasedMetricSpecDict",
    "LLMBasedMetricSpecOrDict",
    "CustomCodeExecutionSpec",
    "CustomCodeExecutionSpecDict",
    "CustomCodeExecutionSpecOrDict",
    "UnifiedMetric",
    "UnifiedMetricDict",
    "UnifiedMetricOrDict",
    "EvaluationRunMetric",
    "EvaluationRunMetricDict",
    "EvaluationRunMetricOrDict",
    "EvaluationRunConfig",
    "EvaluationRunConfigDict",
    "EvaluationRunConfigOrDict",
    "CreateEvaluationRunConfig",
    "CreateEvaluationRunConfigDict",
    "CreateEvaluationRunConfigOrDict",
    "SummaryMetric",
    "SummaryMetricDict",
    "SummaryMetricOrDict",
    "EvaluationRunResults",
    "EvaluationRunResultsDict",
    "EvaluationRunResultsOrDict",
    "ResponseCandidateResult",
    "ResponseCandidateResultDict",
    "ResponseCandidateResultOrDict",
    "EvalCaseResult",
    "EvalCaseResultDict",
    "EvalCaseResultOrDict",
    "AggregatedMetricResult",
    "AggregatedMetricResultDict",
    "AggregatedMetricResultOrDict",
    "ResponseCandidate",
    "ResponseCandidateDict",
    "ResponseCandidateOrDict",
    "EvalCase",
    "EvalCaseDict",
    "EvalCaseOrDict",
    "GcsSource",
    "GcsSourceDict",
    "GcsSourceOrDict",
    "BigQuerySource",
    "BigQuerySourceDict",
    "BigQuerySourceOrDict",
    "EvaluationDataset",
    "EvaluationDatasetDict",
    "EvaluationDatasetOrDict",
    "EvaluationRunMetadata",
    "EvaluationRunMetadataDict",
    "EvaluationRunMetadataOrDict",
    "EvaluationResult",
    "EvaluationResultDict",
    "EvaluationResultOrDict",
    "EvaluationRun",
    "EvaluationRunDict",
    "EvaluationRunOrDict",
    "CreateEvaluationSetConfig",
    "CreateEvaluationSetConfigDict",
    "CreateEvaluationSetConfigOrDict",
    "EvaluationSet",
    "EvaluationSetDict",
    "EvaluationSetOrDict",
    "BleuInstance",
    "BleuInstanceDict",
    "BleuInstanceOrDict",
    "BleuInput",
    "BleuInputDict",
    "BleuInputOrDict",
    "ExactMatchInstance",
    "ExactMatchInstanceDict",
    "ExactMatchInstanceOrDict",
    "ExactMatchSpec",
    "ExactMatchSpecDict",
    "ExactMatchSpecOrDict",
    "ExactMatchInput",
    "ExactMatchInputDict",
    "ExactMatchInputOrDict",
    "RougeInstance",
    "RougeInstanceDict",
    "RougeInstanceOrDict",
    "RougeInput",
    "RougeInputDict",
    "RougeInputOrDict",
    "ContentMap",
    "ContentMapDict",
    "ContentMapOrDict",
    "PointwiseMetricInstance",
    "PointwiseMetricInstanceDict",
    "PointwiseMetricInstanceOrDict",
    "PointwiseMetricInput",
    "PointwiseMetricInputDict",
    "PointwiseMetricInputOrDict",
    "PairwiseMetricInstance",
    "PairwiseMetricInstanceDict",
    "PairwiseMetricInstanceOrDict",
    "PairwiseMetricInput",
    "PairwiseMetricInputDict",
    "PairwiseMetricInputOrDict",
    "ToolCallValidInstance",
    "ToolCallValidInstanceDict",
    "ToolCallValidInstanceOrDict",
    "ToolCallValidSpec",
    "ToolCallValidSpecDict",
    "ToolCallValidSpecOrDict",
    "ToolCallValidInput",
    "ToolCallValidInputDict",
    "ToolCallValidInputOrDict",
    "ToolNameMatchInstance",
    "ToolNameMatchInstanceDict",
    "ToolNameMatchInstanceOrDict",
    "ToolNameMatchSpec",
    "ToolNameMatchSpecDict",
    "ToolNameMatchSpecOrDict",
    "ToolNameMatchInput",
    "ToolNameMatchInputDict",
    "ToolNameMatchInputOrDict",
    "ToolParameterKeyMatchInstance",
    "ToolParameterKeyMatchInstanceDict",
    "ToolParameterKeyMatchInstanceOrDict",
    "ToolParameterKeyMatchSpec",
    "ToolParameterKeyMatchSpecDict",
    "ToolParameterKeyMatchSpecOrDict",
    "ToolParameterKeyMatchInput",
    "ToolParameterKeyMatchInputDict",
    "ToolParameterKeyMatchInputOrDict",
    "ToolParameterKVMatchInstance",
    "ToolParameterKVMatchInstanceDict",
    "ToolParameterKVMatchInstanceOrDict",
    "ToolParameterKVMatchSpec",
    "ToolParameterKVMatchSpecDict",
    "ToolParameterKVMatchSpecOrDict",
    "ToolParameterKVMatchInput",
    "ToolParameterKVMatchInputDict",
    "ToolParameterKVMatchInputOrDict",
    "MapInstance",
    "MapInstanceDict",
    "MapInstanceOrDict",
    "EvaluationInstance",
    "EvaluationInstanceDict",
    "EvaluationInstanceOrDict",
    "EvaluateInstancesConfig",
    "EvaluateInstancesConfigDict",
    "EvaluateInstancesConfigOrDict",
    "RubricBasedMetricSpec",
    "RubricBasedMetricSpecDict",
    "RubricBasedMetricSpecOrDict",
    "RubricEnhancedContents",
    "RubricEnhancedContentsDict",
    "RubricEnhancedContentsOrDict",
    "RubricBasedMetricInstance",
    "RubricBasedMetricInstanceDict",
    "RubricBasedMetricInstanceOrDict",
    "RubricBasedMetricInput",
    "RubricBasedMetricInputDict",
    "RubricBasedMetricInputOrDict",
    "Metric",
    "MetricDict",
    "MetricOrDict",
    "MetricResult",
    "MetricResultDict",
    "MetricResultOrDict",
    "RubricBasedMetricResult",
    "RubricBasedMetricResultDict",
    "RubricBasedMetricResultOrDict",
    "BleuMetricValue",
    "BleuMetricValueDict",
    "BleuMetricValueOrDict",
    "BleuResults",
    "BleuResultsDict",
    "BleuResultsOrDict",
    "CometResult",
    "CometResultDict",
    "CometResultOrDict",
    "ExactMatchMetricValue",
    "ExactMatchMetricValueDict",
    "ExactMatchMetricValueOrDict",
    "ExactMatchResults",
    "ExactMatchResultsDict",
    "ExactMatchResultsOrDict",
    "MetricxResult",
    "MetricxResultDict",
    "MetricxResultOrDict",
    "RawOutput",
    "RawOutputDict",
    "RawOutputOrDict",
    "CustomOutput",
    "CustomOutputDict",
    "CustomOutputOrDict",
    "PairwiseMetricResult",
    "PairwiseMetricResultDict",
    "PairwiseMetricResultOrDict",
    "PointwiseMetricResult",
    "PointwiseMetricResultDict",
    "PointwiseMetricResultOrDict",
    "RougeMetricValue",
    "RougeMetricValueDict",
    "RougeMetricValueOrDict",
    "RougeResults",
    "RougeResultsDict",
    "RougeResultsOrDict",
    "ToolCallValidMetricValue",
    "ToolCallValidMetricValueDict",
    "ToolCallValidMetricValueOrDict",
    "ToolCallValidResults",
    "ToolCallValidResultsDict",
    "ToolCallValidResultsOrDict",
    "ToolNameMatchMetricValue",
    "ToolNameMatchMetricValueDict",
    "ToolNameMatchMetricValueOrDict",
    "ToolNameMatchResults",
    "ToolNameMatchResultsDict",
    "ToolNameMatchResultsOrDict",
    "ToolParameterKeyMatchMetricValue",
    "ToolParameterKeyMatchMetricValueDict",
    "ToolParameterKeyMatchMetricValueOrDict",
    "ToolParameterKeyMatchResults",
    "ToolParameterKeyMatchResultsDict",
    "ToolParameterKeyMatchResultsOrDict",
    "ToolParameterKVMatchMetricValue",
    "ToolParameterKVMatchMetricValueDict",
    "ToolParameterKVMatchMetricValueOrDict",
    "ToolParameterKVMatchResults",
    "ToolParameterKVMatchResultsDict",
    "ToolParameterKVMatchResultsOrDict",
    "EvaluateInstancesResponse",
    "EvaluateInstancesResponseDict",
    "EvaluateInstancesResponseOrDict",
    "RubricGenerationConfig",
    "RubricGenerationConfigDict",
    "RubricGenerationConfigOrDict",
    "GenerateInstanceRubricsResponse",
    "GenerateInstanceRubricsResponseDict",
    "GenerateInstanceRubricsResponseOrDict",
    "GetEvaluationRunConfig",
    "GetEvaluationRunConfigDict",
    "GetEvaluationRunConfigOrDict",
    "GetEvaluationSetConfig",
    "GetEvaluationSetConfigDict",
    "GetEvaluationSetConfigOrDict",
    "GetEvaluationItemConfig",
    "GetEvaluationItemConfigDict",
    "GetEvaluationItemConfigOrDict",
    "OptimizeConfig",
    "OptimizeConfigDict",
    "OptimizeConfigOrDict",
    "OptimizeResponseEndpoint",
    "OptimizeResponseEndpointDict",
    "OptimizeResponseEndpointOrDict",
    "DnsPeeringConfig",
    "DnsPeeringConfigDict",
    "DnsPeeringConfigOrDict",
    "PscInterfaceConfig",
    "PscInterfaceConfigDict",
    "PscInterfaceConfigOrDict",
    "Scheduling",
    "SchedulingDict",
    "SchedulingOrDict",
    "EnvVar",
    "EnvVarDict",
    "EnvVarOrDict",
    "ContainerSpec",
    "ContainerSpecDict",
    "ContainerSpecOrDict",
    "DiskSpec",
    "DiskSpecDict",
    "DiskSpecOrDict",
    "LustreMount",
    "LustreMountDict",
    "LustreMountOrDict",
    "ReservationAffinity",
    "ReservationAffinityDict",
    "ReservationAffinityOrDict",
    "MachineSpec",
    "MachineSpecDict",
    "MachineSpecOrDict",
    "NfsMount",
    "NfsMountDict",
    "NfsMountOrDict",
    "PythonPackageSpec",
    "PythonPackageSpecDict",
    "PythonPackageSpecOrDict",
    "WorkerPoolSpec",
    "WorkerPoolSpecDict",
    "WorkerPoolSpecOrDict",
    "CustomJobSpec",
    "CustomJobSpecDict",
    "CustomJobSpecOrDict",
    "CustomJob",
    "CustomJobDict",
    "CustomJobOrDict",
    "VertexBaseConfig",
    "VertexBaseConfigDict",
    "VertexBaseConfigOrDict",
    "SecretRef",
    "SecretRefDict",
    "SecretRefOrDict",
    "SecretEnvVar",
    "SecretEnvVarDict",
    "SecretEnvVarOrDict",
    "ReasoningEngineSpecDeploymentSpec",
    "ReasoningEngineSpecDeploymentSpecDict",
    "ReasoningEngineSpecDeploymentSpecOrDict",
    "ReasoningEngineSpecPackageSpec",
    "ReasoningEngineSpecPackageSpecDict",
    "ReasoningEngineSpecPackageSpecOrDict",
    "ReasoningEngineSpecSourceCodeSpecInlineSource",
    "ReasoningEngineSpecSourceCodeSpecInlineSourceDict",
    "ReasoningEngineSpecSourceCodeSpecInlineSourceOrDict",
    "ReasoningEngineSpecSourceCodeSpecPythonSpec",
    "ReasoningEngineSpecSourceCodeSpecPythonSpecDict",
    "ReasoningEngineSpecSourceCodeSpecPythonSpecOrDict",
    "ReasoningEngineSpecSourceCodeSpec",
    "ReasoningEngineSpecSourceCodeSpecDict",
    "ReasoningEngineSpecSourceCodeSpecOrDict",
    "ReasoningEngineSpec",
    "ReasoningEngineSpecDict",
    "ReasoningEngineSpecOrDict",
    "MemoryBankCustomizationConfigMemoryTopicCustomMemoryTopic",
    "MemoryBankCustomizationConfigMemoryTopicCustomMemoryTopicDict",
    "MemoryBankCustomizationConfigMemoryTopicCustomMemoryTopicOrDict",
    "MemoryBankCustomizationConfigMemoryTopicManagedMemoryTopic",
    "MemoryBankCustomizationConfigMemoryTopicManagedMemoryTopicDict",
    "MemoryBankCustomizationConfigMemoryTopicManagedMemoryTopicOrDict",
    "MemoryBankCustomizationConfigMemoryTopic",
    "MemoryBankCustomizationConfigMemoryTopicDict",
    "MemoryBankCustomizationConfigMemoryTopicOrDict",
    "MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSourceEvent",
    "MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSourceEventDict",
    "MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSourceEventOrDict",
    "MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSource",
    "MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSourceDict",
    "MemoryBankCustomizationConfigGenerateMemoriesExampleConversationSourceOrDict",
    "MemoryTopicId",
    "MemoryTopicIdDict",
    "MemoryTopicIdOrDict",
    "MemoryBankCustomizationConfigGenerateMemoriesExampleGeneratedMemory",
    "MemoryBankCustomizationConfigGenerateMemoriesExampleGeneratedMemoryDict",
    "MemoryBankCustomizationConfigGenerateMemoriesExampleGeneratedMemoryOrDict",
    "MemoryBankCustomizationConfigGenerateMemoriesExample",
    "MemoryBankCustomizationConfigGenerateMemoriesExampleDict",
    "MemoryBankCustomizationConfigGenerateMemoriesExampleOrDict",
    "MemoryBankCustomizationConfig",
    "MemoryBankCustomizationConfigDict",
    "MemoryBankCustomizationConfigOrDict",
    "ReasoningEngineContextSpecMemoryBankConfigGenerationConfig",
    "ReasoningEngineContextSpecMemoryBankConfigGenerationConfigDict",
    "ReasoningEngineContextSpecMemoryBankConfigGenerationConfigOrDict",
    "ReasoningEngineContextSpecMemoryBankConfigSimilaritySearchConfig",
    "ReasoningEngineContextSpecMemoryBankConfigSimilaritySearchConfigDict",
    "ReasoningEngineContextSpecMemoryBankConfigSimilaritySearchConfigOrDict",
    "ReasoningEngineContextSpecMemoryBankConfigTtlConfigGranularTtlConfig",
    "ReasoningEngineContextSpecMemoryBankConfigTtlConfigGranularTtlConfigDict",
    "ReasoningEngineContextSpecMemoryBankConfigTtlConfigGranularTtlConfigOrDict",
    "ReasoningEngineContextSpecMemoryBankConfigTtlConfig",
    "ReasoningEngineContextSpecMemoryBankConfigTtlConfigDict",
    "ReasoningEngineContextSpecMemoryBankConfigTtlConfigOrDict",
    "ReasoningEngineContextSpecMemoryBankConfig",
    "ReasoningEngineContextSpecMemoryBankConfigDict",
    "ReasoningEngineContextSpecMemoryBankConfigOrDict",
    "ReasoningEngineContextSpec",
    "ReasoningEngineContextSpecDict",
    "ReasoningEngineContextSpecOrDict",
    "CreateAgentEngineConfig",
    "CreateAgentEngineConfigDict",
    "CreateAgentEngineConfigOrDict",
    "ReasoningEngine",
    "ReasoningEngineDict",
    "ReasoningEngineOrDict",
    "AgentEngineOperation",
    "AgentEngineOperationDict",
    "AgentEngineOperationOrDict",
    "DeleteAgentEngineConfig",
    "DeleteAgentEngineConfigDict",
    "DeleteAgentEngineConfigOrDict",
    "DeleteAgentEngineOperation",
    "DeleteAgentEngineOperationDict",
    "DeleteAgentEngineOperationOrDict",
    "GetAgentEngineConfig",
    "GetAgentEngineConfigDict",
    "GetAgentEngineConfigOrDict",
    "ListAgentEngineConfig",
    "ListAgentEngineConfigDict",
    "ListAgentEngineConfigOrDict",
    "ListReasoningEnginesResponse",
    "ListReasoningEnginesResponseDict",
    "ListReasoningEnginesResponseOrDict",
    "GetAgentEngineOperationConfig",
    "GetAgentEngineOperationConfigDict",
    "GetAgentEngineOperationConfigOrDict",
    "QueryAgentEngineConfig",
    "QueryAgentEngineConfigDict",
    "QueryAgentEngineConfigOrDict",
    "QueryReasoningEngineResponse",
    "QueryReasoningEngineResponseDict",
    "QueryReasoningEngineResponseOrDict",
    "UpdateAgentEngineConfig",
    "UpdateAgentEngineConfigDict",
    "UpdateAgentEngineConfigOrDict",
    "AgentEngineMemoryConfig",
    "AgentEngineMemoryConfigDict",
    "AgentEngineMemoryConfigOrDict",
    "Memory",
    "MemoryDict",
    "MemoryOrDict",
    "AgentEngineMemoryOperation",
    "AgentEngineMemoryOperationDict",
    "AgentEngineMemoryOperationOrDict",
    "DeleteAgentEngineMemoryConfig",
    "DeleteAgentEngineMemoryConfigDict",
    "DeleteAgentEngineMemoryConfigOrDict",
    "DeleteAgentEngineMemoryOperation",
    "DeleteAgentEngineMemoryOperationDict",
    "DeleteAgentEngineMemoryOperationOrDict",
    "GenerateMemoriesRequestVertexSessionSource",
    "GenerateMemoriesRequestVertexSessionSourceDict",
    "GenerateMemoriesRequestVertexSessionSourceOrDict",
    "GenerateMemoriesRequestDirectContentsSourceEvent",
    "GenerateMemoriesRequestDirectContentsSourceEventDict",
    "GenerateMemoriesRequestDirectContentsSourceEventOrDict",
    "GenerateMemoriesRequestDirectContentsSource",
    "GenerateMemoriesRequestDirectContentsSourceDict",
    "GenerateMemoriesRequestDirectContentsSourceOrDict",
    "GenerateMemoriesRequestDirectMemoriesSourceDirectMemory",
    "GenerateMemoriesRequestDirectMemoriesSourceDirectMemoryDict",
    "GenerateMemoriesRequestDirectMemoriesSourceDirectMemoryOrDict",
    "GenerateMemoriesRequestDirectMemoriesSource",
    "GenerateMemoriesRequestDirectMemoriesSourceDict",
    "GenerateMemoriesRequestDirectMemoriesSourceOrDict",
    "GenerateAgentEngineMemoriesConfig",
    "GenerateAgentEngineMemoriesConfigDict",
    "GenerateAgentEngineMemoriesConfigOrDict",
    "GenerateMemoriesResponseGeneratedMemory",
    "GenerateMemoriesResponseGeneratedMemoryDict",
    "GenerateMemoriesResponseGeneratedMemoryOrDict",
    "GenerateMemoriesResponse",
    "GenerateMemoriesResponseDict",
    "GenerateMemoriesResponseOrDict",
    "AgentEngineGenerateMemoriesOperation",
    "AgentEngineGenerateMemoriesOperationDict",
    "AgentEngineGenerateMemoriesOperationOrDict",
    "GetAgentEngineMemoryConfig",
    "GetAgentEngineMemoryConfigDict",
    "GetAgentEngineMemoryConfigOrDict",
    "ListAgentEngineMemoryConfig",
    "ListAgentEngineMemoryConfigDict",
    "ListAgentEngineMemoryConfigOrDict",
    "ListReasoningEnginesMemoriesResponse",
    "ListReasoningEnginesMemoriesResponseDict",
    "ListReasoningEnginesMemoriesResponseOrDict",
    "RetrieveMemoriesRequestSimilaritySearchParams",
    "RetrieveMemoriesRequestSimilaritySearchParamsDict",
    "RetrieveMemoriesRequestSimilaritySearchParamsOrDict",
    "RetrieveMemoriesRequestSimpleRetrievalParams",
    "RetrieveMemoriesRequestSimpleRetrievalParamsDict",
    "RetrieveMemoriesRequestSimpleRetrievalParamsOrDict",
    "RetrieveAgentEngineMemoriesConfig",
    "RetrieveAgentEngineMemoriesConfigDict",
    "RetrieveAgentEngineMemoriesConfigOrDict",
    "RetrieveMemoriesResponseRetrievedMemory",
    "RetrieveMemoriesResponseRetrievedMemoryDict",
    "RetrieveMemoriesResponseRetrievedMemoryOrDict",
    "RetrieveMemoriesResponse",
    "RetrieveMemoriesResponseDict",
    "RetrieveMemoriesResponseOrDict",
    "RollbackAgentEngineMemoryConfig",
    "RollbackAgentEngineMemoryConfigDict",
    "RollbackAgentEngineMemoryConfigOrDict",
    "AgentEngineRollbackMemoryOperation",
    "AgentEngineRollbackMemoryOperationDict",
    "AgentEngineRollbackMemoryOperationOrDict",
    "UpdateAgentEngineMemoryConfig",
    "UpdateAgentEngineMemoryConfigDict",
    "UpdateAgentEngineMemoryConfigOrDict",
    "PurgeAgentEngineMemoriesConfig",
    "PurgeAgentEngineMemoriesConfigDict",
    "PurgeAgentEngineMemoriesConfigOrDict",
    "PurgeMemoriesResponse",
    "PurgeMemoriesResponseDict",
    "PurgeMemoriesResponseOrDict",
    "AgentEnginePurgeMemoriesOperation",
    "AgentEnginePurgeMemoriesOperationDict",
    "AgentEnginePurgeMemoriesOperationOrDict",
    "GetAgentEngineMemoryRevisionConfig",
    "GetAgentEngineMemoryRevisionConfigDict",
    "GetAgentEngineMemoryRevisionConfigOrDict",
    "IntermediateExtractedMemory",
    "IntermediateExtractedMemoryDict",
    "IntermediateExtractedMemoryOrDict",
    "MemoryRevision",
    "MemoryRevisionDict",
    "MemoryRevisionOrDict",
    "ListAgentEngineMemoryRevisionsConfig",
    "ListAgentEngineMemoryRevisionsConfigDict",
    "ListAgentEngineMemoryRevisionsConfigOrDict",
    "ListAgentEngineMemoryRevisionsResponse",
    "ListAgentEngineMemoryRevisionsResponseDict",
    "ListAgentEngineMemoryRevisionsResponseOrDict",
    "SandboxEnvironmentSpecCodeExecutionEnvironment",
    "SandboxEnvironmentSpecCodeExecutionEnvironmentDict",
    "SandboxEnvironmentSpecCodeExecutionEnvironmentOrDict",
    "SandboxEnvironmentSpecComputerUseEnvironment",
    "SandboxEnvironmentSpecComputerUseEnvironmentDict",
    "SandboxEnvironmentSpecComputerUseEnvironmentOrDict",
    "SandboxEnvironmentSpec",
    "SandboxEnvironmentSpecDict",
    "SandboxEnvironmentSpecOrDict",
    "CreateAgentEngineSandboxConfig",
    "CreateAgentEngineSandboxConfigDict",
    "CreateAgentEngineSandboxConfigOrDict",
    "SandboxEnvironmentConnectionInfo",
    "SandboxEnvironmentConnectionInfoDict",
    "SandboxEnvironmentConnectionInfoOrDict",
    "SandboxEnvironment",
    "SandboxEnvironmentDict",
    "SandboxEnvironmentOrDict",
    "AgentEngineSandboxOperation",
    "AgentEngineSandboxOperationDict",
    "AgentEngineSandboxOperationOrDict",
    "DeleteAgentEngineSandboxConfig",
    "DeleteAgentEngineSandboxConfigDict",
    "DeleteAgentEngineSandboxConfigOrDict",
    "DeleteAgentEngineSandboxOperation",
    "DeleteAgentEngineSandboxOperationDict",
    "DeleteAgentEngineSandboxOperationOrDict",
    "Metadata",
    "MetadataDict",
    "MetadataOrDict",
    "Chunk",
    "ChunkDict",
    "ChunkOrDict",
    "ExecuteCodeAgentEngineSandboxConfig",
    "ExecuteCodeAgentEngineSandboxConfigDict",
    "ExecuteCodeAgentEngineSandboxConfigOrDict",
    "ExecuteSandboxEnvironmentResponse",
    "ExecuteSandboxEnvironmentResponseDict",
    "ExecuteSandboxEnvironmentResponseOrDict",
    "GetAgentEngineSandboxConfig",
    "GetAgentEngineSandboxConfigDict",
    "GetAgentEngineSandboxConfigOrDict",
    "ListAgentEngineSandboxesConfig",
    "ListAgentEngineSandboxesConfigDict",
    "ListAgentEngineSandboxesConfigOrDict",
    "ListAgentEngineSandboxesResponse",
    "ListAgentEngineSandboxesResponseDict",
    "ListAgentEngineSandboxesResponseOrDict",
    "CreateAgentEngineSessionConfig",
    "CreateAgentEngineSessionConfigDict",
    "CreateAgentEngineSessionConfigOrDict",
    "Session",
    "SessionDict",
    "SessionOrDict",
    "AgentEngineSessionOperation",
    "AgentEngineSessionOperationDict",
    "AgentEngineSessionOperationOrDict",
    "DeleteAgentEngineSessionConfig",
    "DeleteAgentEngineSessionConfigDict",
    "DeleteAgentEngineSessionConfigOrDict",
    "DeleteAgentEngineSessionOperation",
    "DeleteAgentEngineSessionOperationDict",
    "DeleteAgentEngineSessionOperationOrDict",
    "GetAgentEngineSessionConfig",
    "GetAgentEngineSessionConfigDict",
    "GetAgentEngineSessionConfigOrDict",
    "ListAgentEngineSessionsConfig",
    "ListAgentEngineSessionsConfigDict",
    "ListAgentEngineSessionsConfigOrDict",
    "ListReasoningEnginesSessionsResponse",
    "ListReasoningEnginesSessionsResponseDict",
    "ListReasoningEnginesSessionsResponseOrDict",
    "UpdateAgentEngineSessionConfig",
    "UpdateAgentEngineSessionConfigDict",
    "UpdateAgentEngineSessionConfigOrDict",
    "EventActions",
    "EventActionsDict",
    "EventActionsOrDict",
    "EventMetadata",
    "EventMetadataDict",
    "EventMetadataOrDict",
    "AppendAgentEngineSessionEventConfig",
    "AppendAgentEngineSessionEventConfigDict",
    "AppendAgentEngineSessionEventConfigOrDict",
    "AppendAgentEngineSessionEventResponse",
    "AppendAgentEngineSessionEventResponseDict",
    "AppendAgentEngineSessionEventResponseOrDict",
    "ListAgentEngineSessionEventsConfig",
    "ListAgentEngineSessionEventsConfigDict",
    "ListAgentEngineSessionEventsConfigOrDict",
    "SessionEvent",
    "SessionEventDict",
    "SessionEventOrDict",
    "ListAgentEngineSessionEventsResponse",
    "ListAgentEngineSessionEventsResponseDict",
    "ListAgentEngineSessionEventsResponseOrDict",
    "GeminiExample",
    "GeminiExampleDict",
    "GeminiExampleOrDict",
    "GeminiTemplateConfig",
    "GeminiTemplateConfigDict",
    "GeminiTemplateConfigOrDict",
    "GeminiRequestReadConfig",
    "GeminiRequestReadConfigDict",
    "GeminiRequestReadConfigOrDict",
    "AssembleDatasetConfig",
    "AssembleDatasetConfigDict",
    "AssembleDatasetConfigOrDict",
    "MultimodalDatasetOperation",
    "MultimodalDatasetOperationDict",
    "MultimodalDatasetOperationOrDict",
    "TuningResourceUsageAssessmentConfig",
    "TuningResourceUsageAssessmentConfigDict",
    "TuningResourceUsageAssessmentConfigOrDict",
    "TuningValidationAssessmentConfig",
    "TuningValidationAssessmentConfigDict",
    "TuningValidationAssessmentConfigOrDict",
    "BatchPredictionResourceUsageAssessmentConfig",
    "BatchPredictionResourceUsageAssessmentConfigDict",
    "BatchPredictionResourceUsageAssessmentConfigOrDict",
    "BatchPredictionValidationAssessmentConfig",
    "BatchPredictionValidationAssessmentConfigDict",
    "BatchPredictionValidationAssessmentConfigOrDict",
    "AssessDatasetConfig",
    "AssessDatasetConfigDict",
    "AssessDatasetConfigOrDict",
    "SchemaTablesDatasetMetadataBigQuerySource",
    "SchemaTablesDatasetMetadataBigQuerySourceDict",
    "SchemaTablesDatasetMetadataBigQuerySourceOrDict",
    "SchemaTablesDatasetMetadataInputConfig",
    "SchemaTablesDatasetMetadataInputConfigDict",
    "SchemaTablesDatasetMetadataInputConfigOrDict",
    "SchemaTablesDatasetMetadata",
    "SchemaTablesDatasetMetadataDict",
    "SchemaTablesDatasetMetadataOrDict",
    "CreateMultimodalDatasetConfig",
    "CreateMultimodalDatasetConfigDict",
    "CreateMultimodalDatasetConfigOrDict",
    "MultimodalDataset",
    "MultimodalDatasetDict",
    "MultimodalDatasetOrDict",
    "GetMultimodalDatasetOperationConfig",
    "GetMultimodalDatasetOperationConfigDict",
    "GetMultimodalDatasetOperationConfigOrDict",
    "ListMultimodalDatasetsConfig",
    "ListMultimodalDatasetsConfigDict",
    "ListMultimodalDatasetsConfigOrDict",
    "ListMultimodalDatasetsResponse",
    "ListMultimodalDatasetsResponseDict",
    "ListMultimodalDatasetsResponseOrDict",
    "UpdateMultimodalDatasetConfig",
    "UpdateMultimodalDatasetConfigDict",
    "UpdateMultimodalDatasetConfigOrDict",
    "SchemaPredictParamsGroundingConfigSourceEntry",
    "SchemaPredictParamsGroundingConfigSourceEntryDict",
    "SchemaPredictParamsGroundingConfigSourceEntryOrDict",
    "SchemaPredictParamsGroundingConfig",
    "SchemaPredictParamsGroundingConfigDict",
    "SchemaPredictParamsGroundingConfigOrDict",
    "SchemaPromptInstancePromptExecution",
    "SchemaPromptInstancePromptExecutionDict",
    "SchemaPromptInstancePromptExecutionOrDict",
    "SchemaPromptSpecPromptMessage",
    "SchemaPromptSpecPromptMessageDict",
    "SchemaPromptSpecPromptMessageOrDict",
    "SchemaPromptSpecMultimodalPrompt",
    "SchemaPromptSpecMultimodalPromptDict",
    "SchemaPromptSpecMultimodalPromptOrDict",
    "SchemaPromptSpecPartList",
    "SchemaPromptSpecPartListDict",
    "SchemaPromptSpecPartListOrDict",
    "SchemaPromptSpecStructuredPrompt",
    "SchemaPromptSpecStructuredPromptDict",
    "SchemaPromptSpecStructuredPromptOrDict",
    "SchemaPromptSpecReferenceSentencePair",
    "SchemaPromptSpecReferenceSentencePairDict",
    "SchemaPromptSpecReferenceSentencePairOrDict",
    "SchemaPromptSpecReferenceSentencePairList",
    "SchemaPromptSpecReferenceSentencePairListDict",
    "SchemaPromptSpecReferenceSentencePairListOrDict",
    "SchemaPromptSpecTranslationFileInputSource",
    "SchemaPromptSpecTranslationFileInputSourceDict",
    "SchemaPromptSpecTranslationFileInputSourceOrDict",
    "SchemaPromptSpecTranslationGcsInputSource",
    "SchemaPromptSpecTranslationGcsInputSourceDict",
    "SchemaPromptSpecTranslationGcsInputSourceOrDict",
    "SchemaPromptSpecTranslationSentenceFileInput",
    "SchemaPromptSpecTranslationSentenceFileInputDict",
    "SchemaPromptSpecTranslationSentenceFileInputOrDict",
    "SchemaPromptSpecTranslationExample",
    "SchemaPromptSpecTranslationExampleDict",
    "SchemaPromptSpecTranslationExampleOrDict",
    "SchemaPromptSpecTranslationOption",
    "SchemaPromptSpecTranslationOptionDict",
    "SchemaPromptSpecTranslationOptionOrDict",
    "SchemaPromptSpecTranslationPrompt",
    "SchemaPromptSpecTranslationPromptDict",
    "SchemaPromptSpecTranslationPromptOrDict",
    "SchemaPromptApiSchema",
    "SchemaPromptApiSchemaDict",
    "SchemaPromptApiSchemaOrDict",
    "SchemaTextPromptDatasetMetadata",
    "SchemaTextPromptDatasetMetadataDict",
    "SchemaTextPromptDatasetMetadataOrDict",
    "CreateDatasetConfig",
    "CreateDatasetConfigDict",
    "CreateDatasetConfigOrDict",
    "DatasetOperation",
    "DatasetOperationDict",
    "DatasetOperationOrDict",
    "CreateDatasetVersionConfig",
    "CreateDatasetVersionConfigDict",
    "CreateDatasetVersionConfigOrDict",
    "SavedQuery",
    "SavedQueryDict",
    "SavedQueryOrDict",
    "Dataset",
    "DatasetDict",
    "DatasetOrDict",
    "DatasetVersion",
    "DatasetVersionDict",
    "DatasetVersionOrDict",
    "GetDatasetOperationConfig",
    "GetDatasetOperationConfigDict",
    "GetDatasetOperationConfigOrDict",
    "ListPromptsConfig",
    "ListPromptsConfigDict",
    "ListPromptsConfigOrDict",
    "ListDatasetsResponse",
    "ListDatasetsResponseDict",
    "ListDatasetsResponseOrDict",
    "ListDatasetVersionsResponse",
    "ListDatasetVersionsResponseDict",
    "ListDatasetVersionsResponseOrDict",
    "DeletePromptConfig",
    "DeletePromptConfigDict",
    "DeletePromptConfigOrDict",
    "DeletePromptOperation",
    "DeletePromptOperationDict",
    "DeletePromptOperationOrDict",
    "DeletePromptVersionOperation",
    "DeletePromptVersionOperationDict",
    "DeletePromptVersionOperationOrDict",
    "RestoreVersionConfig",
    "RestoreVersionConfigDict",
    "RestoreVersionConfigOrDict",
    "RestoreVersionOperation",
    "RestoreVersionOperationDict",
    "RestoreVersionOperationOrDict",
    "UpdateDatasetConfig",
    "UpdateDatasetConfigDict",
    "UpdateDatasetConfigOrDict",
    "PromptOptimizerConfig",
    "PromptOptimizerConfigDict",
    "PromptOptimizerConfigOrDict",
    "ApplicableGuideline",
    "ApplicableGuidelineDict",
    "ApplicableGuidelineOrDict",
    "ParsedResponse",
    "ParsedResponseDict",
    "ParsedResponseOrDict",
    "OptimizeResponse",
    "OptimizeResponseDict",
    "OptimizeResponseOrDict",
    "PromptTemplate",
    "PromptTemplateDict",
    "PromptTemplateOrDict",
    "EvalRunInferenceConfig",
    "EvalRunInferenceConfigDict",
    "EvalRunInferenceConfigOrDict",
    "ContentMapContents",
    "ContentMapContentsDict",
    "ContentMapContentsOrDict",
    "EvalCaseMetricResult",
    "EvalCaseMetricResultDict",
    "EvalCaseMetricResultOrDict",
    "EvaluationRunAgentConfig",
    "EvaluationRunAgentConfigDict",
    "EvaluationRunAgentConfigOrDict",
    "EvaluationRunInferenceConfig",
    "EvaluationRunInferenceConfigDict",
    "EvaluationRunInferenceConfigOrDict",
    "WinRateStats",
    "WinRateStatsDict",
    "WinRateStatsOrDict",
    "EvaluateMethodConfig",
    "EvaluateMethodConfigDict",
    "EvaluateMethodConfigOrDict",
    "EvaluateDatasetConfig",
    "EvaluateDatasetConfigDict",
    "EvaluateDatasetConfigOrDict",
    "EvaluateDatasetRequestParameters",
    "EvaluateDatasetRequestParametersDict",
    "EvaluateDatasetRequestParametersOrDict",
    "EvaluateDatasetOperation",
    "EvaluateDatasetOperationDict",
    "EvaluateDatasetOperationOrDict",
    "ObservabilityEvalCase",
    "ObservabilityEvalCaseDict",
    "ObservabilityEvalCaseOrDict",
    "RubricGroup",
    "RubricGroupDict",
    "RubricGroupOrDict",
    "AgentEngine",
    "AgentEngineDict",
    "AgentEngineOrDict",
    "AgentEngineConfig",
    "AgentEngineConfigDict",
    "AgentEngineConfigOrDict",
    "AssembleDataset",
    "AssembleDatasetDict",
    "AssembleDatasetOrDict",
    "BatchPredictionResourceUsageAssessmentResult",
    "BatchPredictionResourceUsageAssessmentResultDict",
    "BatchPredictionResourceUsageAssessmentResultOrDict",
    "TuningResourceUsageAssessmentResult",
    "TuningResourceUsageAssessmentResultDict",
    "TuningResourceUsageAssessmentResultOrDict",
    "TuningValidationAssessmentResult",
    "TuningValidationAssessmentResultDict",
    "TuningValidationAssessmentResultOrDict",
    "Prompt",
    "PromptDict",
    "PromptOrDict",
    "SchemaPromptInstanceVariableValue",
    "SchemaPromptInstanceVariableValueDict",
    "SchemaPromptInstanceVariableValueOrDict",
    "CreatePromptConfig",
    "CreatePromptConfigDict",
    "CreatePromptConfigOrDict",
    "CreatePromptVersionConfig",
    "CreatePromptVersionConfigDict",
    "CreatePromptVersionConfigOrDict",
    "GetPromptConfig",
    "GetPromptConfigDict",
    "GetPromptConfigOrDict",
    "PromptRef",
    "PromptRefDict",
    "PromptRefOrDict",
    "PromptVersionRef",
    "PromptVersionRefDict",
    "PromptVersionRefOrDict",
    "PairwiseChoice",
    "Strategy",
    "AcceleratorType",
    "Type",
    "JobState",
    "IdentityType",
    "AgentServerMode",
    "ManagedTopicEnum",
    "Language",
    "MachineConfig",
    "State",
    "EvaluationItemType",
    "SamplingMethod",
    "RubricContentType",
    "EvaluationRunState",
    "OptimizeTarget",
    "GenerateMemoriesResponseGeneratedMemoryAction",
    "PromptOptimizerMethod",
    "PromptData",
    "PromptDataDict",
    "PromptDataOrDict",
    "LLMMetric",
    "MetricPromptBuilder",
    "RubricContentProperty",
    "RubricContentPropertyDict",
    "RubricContent",
    "RubricContentDict",
    "Rubric",
    "RubricDict",
    "RubricVerdict",
    "RubricVerdictDict",
    "CandidateResult",
    "CandidateResultDict",
    "Event",
    "EventDict",
    "Message",
    "MessageDict",
    "Importance",
    "_CreateEvaluationItemParameters",
    "_CreateEvaluationRunParameters",
    "_CreateEvaluationSetParameters",
    "_EvaluateInstancesRequestParameters",
    "_GenerateInstanceRubricsRequest",
    "_GetEvaluationRunParameters",
    "_GetEvaluationSetParameters",
    "_GetEvaluationItemParameters",
    "_OptimizeRequestParameters",
    "_CustomJobParameters",
    "_GetCustomJobParameters",
    "_CreateAgentEngineRequestParameters",
    "_DeleteAgentEngineRequestParameters",
    "_GetAgentEngineRequestParameters",
    "_ListAgentEngineRequestParameters",
    "_GetAgentEngineOperationParameters",
    "_QueryAgentEngineRequestParameters",
    "_UpdateAgentEngineRequestParameters",
    "_CreateAgentEngineMemoryRequestParameters",
    "_DeleteAgentEngineMemoryRequestParameters",
    "_GenerateAgentEngineMemoriesRequestParameters",
    "_GetAgentEngineMemoryRequestParameters",
    "_ListAgentEngineMemoryRequestParameters",
    "_GetAgentEngineMemoryOperationParameters",
    "_GetAgentEngineGenerateMemoriesOperationParameters",
    "_RetrieveAgentEngineMemoriesRequestParameters",
    "_RollbackAgentEngineMemoryRequestParameters",
    "_UpdateAgentEngineMemoryRequestParameters",
    "_PurgeAgentEngineMemoriesRequestParameters",
    "_GetAgentEngineMemoryRevisionRequestParameters",
    "_ListAgentEngineMemoryRevisionsRequestParameters",
    "_CreateAgentEngineSandboxRequestParameters",
    "_DeleteAgentEngineSandboxRequestParameters",
    "_ExecuteCodeAgentEngineSandboxRequestParameters",
    "_GetAgentEngineSandboxRequestParameters",
    "_ListAgentEngineSandboxesRequestParameters",
    "_GetAgentEngineSandboxOperationParameters",
    "_CreateAgentEngineSessionRequestParameters",
    "_DeleteAgentEngineSessionRequestParameters",
    "_GetAgentEngineSessionRequestParameters",
    "_ListAgentEngineSessionsRequestParameters",
    "_GetAgentEngineSessionOperationParameters",
    "_UpdateAgentEngineSessionRequestParameters",
    "_AppendAgentEngineSessionEventRequestParameters",
    "_ListAgentEngineSessionEventsRequestParameters",
    "_AssembleDatasetParameters",
    "_AssessDatasetParameters",
    "_CreateMultimodalDatasetParameters",
    "_DeleteMultimodalDatasetRequestParameters",
    "_GetMultimodalDatasetParameters",
    "_GetMultimodalDatasetOperationParameters",
    "_ListMultimodalDatasetsRequestParameters",
    "_UpdateMultimodalDatasetParameters",
    "_CreateDatasetParameters",
    "_CreateDatasetVersionParameters",
    "_GetDatasetParameters",
    "_GetDatasetVersionParameters",
    "_GetDatasetOperationParameters",
    "_ListDatasetsRequestParameters",
    "_ListDatasetVersionsRequestParameters",
    "_DeleteDatasetRequestParameters",
    "_DeletePromptVersionRequestParameters",
    "_RestoreVersionRequestParameters",
    "_UpdateDatasetParameters",
    "evals",
    "agent_engines",
    "PrebuiltMetric",
    "RubricMetric",
]


def __getattr__(name: str) -> typing.Any:
    if name == "PrebuiltMetric" or name == "RubricMetric":
        module = importlib.import_module(".._evals_metric_loaders", __package__)
        prebuilt_metric_obj = getattr(module, name)
        globals()[name] = prebuilt_metric_obj
        return prebuilt_metric_obj
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
